<section id="hero" class="hero">
    <div id="img-back">
        <div class="cnt-hero-content">
            <div class="hero-box">
                <div class="container">
                    <div class="hero-text align-center">
                        <h1>Creative Multipurpose Software Template</h1>
                        <p>Connect with your clients in a different way</p>
                    </div>
                    <div class="action-main">
                        <a href="#0" class="no-decoration cnt-btn">See pricing</a>
                    </div>
                </div>
                <div class="wheel-wrap">
                    <span class="mousewheel"></span>
                </div>
            </div>
        </div>
        <!-- //.cnt-hero-bg -->
    </div>
    <!-- //.img-back -->
</section>
<section id="services">
    <div class="cnt-services-bg">
        <div class="container">
            <h1>Our services</h1>
            <p class="title-txt">Get amazing product with an excellent service</p>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered item-container">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
                        <i class="pe-7s-call"></i>
                        <h2>Answering Services</h2>
                        <p class="items">Loasellus id ligula hendrerit, pulvinar eros nec, vulputate metus. Sequam sed metus indum sagittis</p>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
                        <i class="pe-7s-headphones"></i>
                        <h2>Call center solutions</h2>
                        <p class="items">Loasellus id ligula hendrerit, pulvinar eros nec, vulputate metus. Sequam sed metus indum sagittis</p>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
                        <i class="pe-7s-cloud-upload"></i>
                        <h2>Upload data</h2>
                        <p class="items">Loasellus id ligula hendrerit, pulvinar eros nec, vulputate metus. Sequam sed metus indum sagittis</p>
                    </div>
                </div>
                <!-- //.item-container -->
                <div class="col-lg-12 action-started">
                    <a href="#" class="btn btn-outlined">Get started</a>
                </div>
            </div>
            <!-- //.row -->
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-services-bg -->
</section>
<section id="features">
    <div class="cnt-features-bg">
        <div class="container">
            <h1>Features</h1>
            <p>Project Management with <b id="word-rotate">Analytics, Creativity, Performance, Design</b></p>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 item-cnt-feature">
                    <!-- Left -->
                    <div class="col-md-6 col-lg-6">
                        <!-- item init -->
                        <div class="col-md-12 col-lg-12 icon-box">
                            <div class="col-md-2 col-lg-2">
                                <div class="icon">
                                    <i class="pe-7s-help2"></i>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 left-icon-text">
                                <h2>24x7x35</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, adipiscing elit.</p>
                            </div>
                        </div>
                        <!-- //item init -->
                        <!-- item init -->
                        <div class="col-md-12 col-lg-12 icon-box">
                            <div class="col-md-2 col-lg-2">
                                <div class="icon">
                                    <i class="pe-7s-bell"></i>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 left-icon-text">
                                <h2>Smart Notifications</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, adipiscing elit.</p>
                            </div>
                        </div>
                        <!-- //item init -->
                        <!-- item init -->
                        <div class="col-md-12 col-lg-12 icon-box">
                            <div class="col-md-2 col-lg-2">
                                <div class="icon">
                                    <i class="pe-7s-server"></i>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 left-icon-text">
                                <h2>Export Data</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, adipiscing elit.</p>
                            </div>
                        </div>
                        <!-- //item init -->
                    </div>
                    <!-- //Left -->
                    <!-- Right -->
                    <div class="col-md-6 col-lg-6 side-img">
                        <img src="assets/img/dashboard.png" alt="" class="img-responsive">
                    </div>
                    <!-- //Right -->
                </div>
            </div>
            <div class="col-lg-12 action-started">
                <a href="#" class="btn btn-outlined">Find out more</a>
            </div>
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-features-bg -->
</section>
<section id="stats" class="stats">
    <div class="cnt-stats-bg">
        <div class="container">
            <h1>Strong Numbers</h1>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 item-container">
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 item-stats">
                        <i class="pe-7s-gleam"></i>
                        <h2><span class="counter">50</span>M</h2>
                        <p class="items">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 item-stats">
                        <i class="pe-7s-chat"></i>
                        <h2><span class="counter">95</span>%</h2>
                        <p class="items">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 item-stats">
                        <i class="pe-7s-cart"></i>
                        <h2><span class="counter">25</span>K</h2>
                        <p class="items">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </div>
                </div>
            </div>
            <!-- //.row -->
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-stats-bg -->
</section>
<section id="testimonials">
    <div class="cnt-testimonials-bg">
        <div class="container">
            <h1>Client's Feedback</h1>
            <div class="row">
                <div class="col-md-12 col-lg-12 items-testimonials">
                    <!-- item testimonial -->
                    <div class="col-md-4 col-lg-4 item-testimonial">
                        <div class="txt-testimonial">
                            <p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree cursus erat et faucibus tempus. Pellentesximus dolor eget erat bibeus. Ut vel nunc vel augue mattis aliquet.</p>
                        </div>
                        <div class="testimonial">
                            <img src="assets/img/client-face1.png" alt="" class="img-responsive" width="100" height="100">
                            <p class="name">Jane Doe</p>
                            <cite>CEO, Impromptu</cite>
                        </div>
                    </div>
                    <!-- //item testimonial -->
                    <!-- item testimonial -->
                    <div class="col-md-4 col-lg-4 item-testimonial">
                        <div class="txt-testimonial">
                            <p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree cursus erat et faucibus tempus. Pellentesximus dolor eget erat bibeus. Ut vel nunc vel augue mattis aliquet.</p>
                        </div>
                        <div class="testimonial">
                            <img src="assets/img/client-face2.png" alt="" class="img-responsive" width="100" height="100">
                            <p class="name">John Doe</p>
                            <cite>CTO, CitrusLabs</cite>
                        </div>
                    </div>
                    <!-- //item testimonial -->
                    <!-- item testimonial -->
                    <div class="col-md-4 col-lg-4 item-testimonial">
                        <div class="txt-testimonial">
                            <p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree cursus erat et faucibus tempus. Pellentesximus dolor eget erat bibeus. Ut vel nunc vel augue mattis aliquet.</p>
                        </div>
                        <div class="testimonial">
                            <img src="assets/img/client-face3.png" alt="" class="img-responsive" width="100" height="100">
                            <p class="name">Richard Hendricks</p>
                            <cite>CEO, Pied Piper</cite>
                        </div>
                    </div>
                    <!-- //item testimonial -->
                </div>
            </div>
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-testimonials-bg -->
</section>
<section data-sr id="video" class="video u-full-width featured-bg-image">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Quick Video Demonstration</h2>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 btn-circle-play">
                <a href="https://www.youtube.com/embed/6NC_ODHu5jg?autoplay=1" class="fancybox.iframe">
                    <div class="hero-mat">
                        <i class="pe-7s-play play-button"></i>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
<section id="pricing">
    <div class="cnt-pricing-bg">
        <div class="container">
            <h1>Pricing Packages</h1>
            <p class="top-txt">Always know what you'll pay</p>
            <div class="row pricing-content">
                <div class="pricing-tables col-md-12 col-lg-12 group">
                    <div class="col-md-3 col-lg-3 bgrid">
                        <div class="price-block">
                            <div class="top-part">
                                <h3 class="plan-title">Starter</h3>
                                <p class="price-txt">Perfect for lorem ipsum businesses of all size</p>
                                <p class="plan-price">$ 4.99 <span>/per month</span></p>
                            </div>
                            <div class="bottom-part">
                                <ul class="features">
                                    <li><strong>3GB</strong> Storage</li>
                                    <li><strong>10GB</strong> Bandwidth</li>
                                    <li><strong>5</strong> Databases</li>
                                    <li><strong>30</strong> Email Accounts</li>
                                </ul>
                                <a class="button" href="#">Get Started</a>
                            </div>
                        </div>
                    </div>
                    <!-- /price-block -->
                    <div class="col-md-3 col-lg-3 bgrid">
                        <div class="price-block primary">
                            <div class="top-part" data-info="recommended">
                                <h3 class="plan-title">Standard</h3>
                                <p class="price-txt">Perfect for lorem ipsum businesses of all size</p>
                                <p class="plan-price">$ 14.99 <span>/per month</span></p>
                            </div>
                            <div class="bottom-part">
                                <ul class="features">
                                    <li><strong>5GB</strong> Storage</li>
                                    <li><strong>15GB</strong> Bandwidth</li>
                                    <li><strong>7</strong> Databases</li>
                                    <li><strong>40</strong> Email Accounts</li>
                                </ul>
                                <a class="button large" href="#">Get Started</a>
                            </div>
                        </div>
                    </div>
                    <!-- /price-block -->
                    <div class="col-md-3 col-lg-3 bgrid">
                        <div class="price-block">
                            <div class="top-part">
                                <h3 class="plan-title">Plus</h3>
                                <p class="price-txt">Perfect for lorem ipsum businesses of all size</p>
                                <p class="plan-price">$ 19.99 <span>/per month</span></p>
                            </div>
                            <div class="bottom-part">
                                <ul class="features">
                                    <li><strong>10GB</strong> Storage</li>
                                    <li><strong>30GB</strong> Bandwidth</li>
                                    <li><strong>15</strong> Databases</li>
                                    <li><strong>60</strong> Email Accounts</li>
                                </ul>
                                <a class="button large" href="#">Get Started</a>
                            </div>
                        </div>
                    </div>
                    <!-- /price-block -->
                    <div class="col-md-3 col-lg-3 bgrid">
                        <div class="price-block">
                            <div class="top-part">
                                <h3 class="plan-title">Ultimate</h3>
                                <p class="price-txt">Perfect for lorem ipsum businesses of all size</p>
                                <p class="plan-price">$ 29.99 <span>/per month</span></p>
                            </div>
                            <div class="bottom-part">
                                <ul class="features">
                                    <li><strong>20GB</strong> Storage</li>
                                    <li><strong>40GB</strong> Bandwidth</li>
                                    <li><strong>25</strong> Databases</li>
                                    <li><strong>100</strong> Email Accounts</li>
                                </ul>
                                <a class="button large" href="#">Get Started</a>
                            </div>
                        </div>
                    </div>
                    <!-- /price-block -->
                </div>
                <!-- /pricing-tables -->
            </div>
            <!-- /pricing-content -->
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-pricing-bg -->
</section>
<section id="subscribe">
    <div class="cnt-subscribe-bg">
        <div class="container">
            <h1>Subscribe to our updates</h1>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <p>Suspendisse a arcu efficitur erat auctor viverra. Morbi molestie arcu vitae dolor mollis iaculis vulputate at ante auctor, bibendum dapibus augue</p>
                </div>
                <div class="col-lg-6 formi">
                    <form class="subscribe-form">
                        <div class="input-line">
                            <input type="text" name="subscribe-email" value="" placeholder="Your email address" />
                        </div>
                        <button type="button" name="subscribe-submit" class="btn btn-special no-icon">Subscribe</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-subscribe-bg -->
</section>
<div id="map-location">
    <div class="cnt-map-bg">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-lg-12 map-google">
                    <div id="map"></div>
                </div>
            </div>
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-map-bg -->
</div>
<section id="sblog">
    <div class="cnt-sblog-bg">
        <div class="container">
            <h1>Our Blog</h1>
            <p class="title-txt">Read our latest posts</p>
            <div class="row-centered">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered cnt-blog-wg">
                    <!-- Block 1 -->
                    <div class="col-md-4 col-lg-4 cnt-post">
                        <div class="fit_image">
                            <img src="assets/img/quote.jpg" alt="" class="img-responsive">
                        </div>
                        <h2>How to read to learn and exercise</h2>
                        <p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree
                        </p>
                        <ul class="data-post">
                            <li>November 2015</li>
                            <li class="separator-post"><i class="fa fa-circle"></i></li>
                            <li class="category">Tech Industry</li>
                        </ul>
                        <a href="blog-single-post.html"><span class="read-more">Read More <i class="fa fa-angle-right"></i></span></a>
                    </div>
                    <!-- //Block 1 -->
                    <!-- Block 2 -->
                    <div class="col-md-4 col-lg-4 cnt-post">
                        <div class="fit_image">
                            <img src="assets/img/quote.jpg" alt="" class="img-responsive">
                        </div>
                        <h2>Timing is Everything for the Eastern Wolf</h2>
                        <p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree
                        </p>
                        <ul class="data-post">
                            <li>November 2015</li>
                            <li class="separator-post"><i class="fa fa-circle"></i></li>
                            <li class="category">Tech Industry</li>
                        </ul>
                        <a href="blog-single-post.html"><span class="read-more">Read More <i class="fa fa-angle-right"></i></span></a>
                    </div>
                    <!-- //Block 2 -->
                    <!-- Block 3 -->
                    <div class="col-md-4 col-lg-4 cnt-post">
                        <div class="fit_image">
                            <img src="assets/img/quote.jpg" alt="" class="img-responsive">
                        </div>
                        <h2>A look inside amazing offices</h2>
                        <p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree
                        </p>
                        <ul class="data-post">
                            <li>November 2015</li>
                            <li class="separator-post"><i class="fa fa-circle"></i></li>
                            <li class="category">Tech Industry</li>
                        </ul>
                        <a href="blog-single-post.html"><span class="read-more">Read More <i class="fa fa-angle-right"></i></span></a>
                    </div>
                    <!-- //Block 3 -->
                </div>
            </div>
            <!-- //.row -->
            <div class="col-lg-12 action-started">
                <a href="#" class="btn btn-outlined">Read all posts</a>
            </div>
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-sblog-bg -->
</section>
<section id="started">
    <div class="cnt-started-bg">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h2>Sign up it takes only 10 minutes</h2>
                    <div class="col-lg-12 action-started">
                        <a href="#" class="btn btn-outlined">Get started</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-started-bg -->
</section>