<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">
        </div>
    </div>
</section>


<section id="post-blog" class="main-post">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 container-post">
                    <ul class="blog-data">
                        <div class="row" style="text-align: center; margin: auto;>
							<div class=">
                            <h4 style="color: #21DC7F; font-family: 'Montserrat',sans-serif; letter-spacing: 1px; font-size: 2.5rem; padding-bottom: 1.2rem; margin-bottom: 1.2rem;">
                                Benvenuto, ecco la lista dei blog degli iscritti!</h4>
                            <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                                   width="100%">
                                <thead>
                                <tr>
                                    <th class="font-tabella" style="text-align: center">Utente</th>
                                    <?php if (count($this->blogSet) > 0): ?>
                                        <th class="font-tabella" style="text-align: center">Blog</th>
                                        <th class="font-tabella" style="text-align: center">Tema</th>
                                        <th class="font-tabella" style="text-align: center">Apri</th>
                                        <th class="font-tabella" style="text-align: center">Elimina</th>
                                    <?php endif; ?>
                                </tr>
                                </thead>

                                <tbody>
                                <tr>
                                    <?php if (count($this->blogSet) == 0): ?>
                                        <td class="font-tabella-campi"
                                            style="font-size: 1.4rem;">Non ci sono blog da visualizzare.
                                        </td>
                                    <?php else: ?>
                                    <?php for ($i = 0;
                                    $i < count($this->blogSet);
                                    $i++): ?>
                                    <td class="font-tabella-campi"
                                        style="font-size: 1.4rem"><?php echo $this->blogSet[$i]['utente']; ?></td>
                                    <td class="font-tabella-campi"
                                        style="font-size: 1.4rem;"><?php echo $this->blogSet[$i]['titolo']; ?></td>
                                    <td class="font-tabella-campi"
                                        style="font-size: 1.4rem;"><?php echo $this->blogSet[$i]['tema']; ?></td>
                                    <td style="font-size: 1.2em;">
                                        <a href="#<?php /*echo $this->url(array(
                                            'controller' => 'staff',
                                            'action' => 'contenutoblog',
                                            "blog" => $this->blogSet[$i]['idblog']));*/
                                        ?>" class="elimina" id="<?php echo $this->blogSet[$i]['idblog'];?>" >
                                            <span>
                                                <i class="fa fa-arrow-right"
                                                   style="color: #21DC7F; font-size: 1.4em"></i>
                                            </span>
                                        </a>
                                    </td>
                                    <td style="font-size: 1.2em;">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'staff',
                                            'action' => 'eliminablog',
                                            'blog' => $this->blogSet[$i]['idblog']));
                                        ?>">
                                            <span>
                                                <i class="fa fa-times-circle"
                                                   style="color: #761c19; font-size: 1.4em"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                                <?php endfor; ?>
                                <?php endif;
                                ?>
                                </tbody>
                            </table>
                        </div>
                </div>
                </ul>
            </div>
        </div>
    </div>
</section>

<script>
    $(".elimina").click(function (event) {
        event.preventDefault();
        id = event.target.id;
        swal({
                title: "Stai eliminando un blog!",
                text: "Inserisci una motivazione che verrà recapitata all'utente:",
                type: "input",
                showCancelButton: true,
                closeOnConfirm: false,
                animation: "slide-from-top",
                inputPlaceholder: "Scrivi qui la motivazione..."
            },
            function(inputValue){
                if (inputValue === false) return false;

                if (inputValue === "") {
                    swal.showInputError("Questo campo non può restare vuoto!");
                    return false
                }
                swal("Cancellazione completata!", "Blog eliminato causa " + inputValue + ".", "success");
            },
            function(){
                $.ajax({
                    type: 'POST',
                    url: eliminaUrl(id),
                    data: id,
                    dataType: 'json',
                    success: messaggioSuccesso(),
                    error: function (xhr) {
                        console.log(xhr.responseText);
                    }
                })
            });
        function eliminaUrl(id) {
            title = "<?php echo $this->url(array(
                'controller' => 'user',
                'action' => 'eliminablog'
            )); ?>";
            params = '/blog/'.concat(id);
            return title.concat(params);
        }
        function messaggioSuccesso() {
            swal("Cancellato!", "Il tuo blog è stato cancellato.", "success");
            setTimeout(location.reload.bind(location),1000);
        }
        function messaggioErrore() {
            swal("Oops...", "Qualcosa è andato storto!", "error");
        }
    });
</script>