<html>
<head>
</head>
<body>

<!-- Slider -->
<div class="hero--slider" id="hero-4">
    <article class="hero">
        <div class="cnt-heroslider-bg" style="background-image: url('image/business.jpg');"></div>
        <div class="main-container">
            <div class="hero-content">
                <h1 class="heroslider_title animated fadeInUp">Raffaello</h1>
                <p class="heroslider_txt animated fadeInRight">Il social network.</p>
                <div class="work-btns align-center animated fadeInLeft">
                    <a href="<?php echo $this->url(
                        array(
                            'controller' => 'public',
                            'action' => 'register',
                        )
                    ); ?>" class="no-decoration cnt-btn active-btn">Iscriviti</a>
                    <a href="<?php echo $this->baseUrl("doc/doc.pdf"); ?>" class="no-decoration cnt-btn">Documentazione progetto</a>
                </div>
            </div>
        </div>
    </article>
    <article class="hero">
        <div class="cnt-heroslider-bg" style="background-image: url('image/quote.jpg');"></div>
        <div class="row">
            <div class="main-container">
                <div class="hero-content-split">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <h2 class="herosplit_title">TekLab</h2>
                        <p class="herosplit_txt">Soluzioni software per la piccola e media impresa.</p>
                        <div class="work-split-btn">
                            <a href="#0" class="no-decoration cnt-btn active-btn">Chi siamo</a>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 mobiles animated fadeInUp">
                        <img src="<?php echo $this->baseUrl("image/devices3.png"); ?>" class="img-responsive"
                             alt="devices"/>
                    </div>
                </div>
            </div>
        </div>
    </article>
</div>

<!-- Servizi-->
<section id="services">
    <div class="cnt-services-bg">
        <div class="container">
            <h1>Cosa facciamo</h1>
            <p class="title-txt">Soluzioni software complete per ogni esigenza.</p>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered item-container">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
                        <i class="pe-7s-call"></i>
                        <h2>Linea diretta</h2>
                        <p class="items">I nostri clienti possono avere sempre a loro disposizione i nsotri tecnici per
                            ogni problema.</p>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
                        <i class="pe-7s-headphones"></i>
                        <h2>Formazione e-learnig</h2>
                        <p class="items">Soluzioni di e-learning per l'apprendimento delle nostre piattaforme.</p>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
                        <i class="pe-7s-cloud-upload"></i>
                        <h2>Soluzioni cloud</h2>
                        <p class="items">Crediamo nel cloud e lo rendiamo disponibile per tutti i nostri prodotti.</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<!-- Get started -->
<section id="started">
    <div class="cnt-started-bg">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h2>Registrati in pochi minuti e inzia a pubblicare anche tu!</h2>
                    <div class="col-lg-12 action-started">
                        <a href="<?php echo $this->url(
                            array(
                                'controller' => 'public',
                                'action' => 'register',
                            )
                        ); ?>" class="btn btn-outlined">Registrazione</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

</body>
</html>