<html>
<head>
</head>
<body>

<!-- Slider -->
<div class="hero--slider" id="hero-4">
	<article class="hero">
		<div class="cnt-heroslider-bg" style="background-image: url('assets/img/business.jpg');"></div>
		<div class="main-container">
			<div class="hero-content">
				<h1 class="heroslider_title animated fadeInUp">Raffaello</h1>
				<p class="heroslider_txt animated fadeInRight">Il social network.</p>
				<div class="work-btns align-center animated fadeInLeft">
					<a href="<?php echo $this->url(
						array(
							'controller' => 'public',
							'action' => 'register',
						)
					); ?>" class="no-decoration cnt-btn active-btn">Iscriviti</a>
					<a href="<?php echo $this->url(
						array(
							'controller' => 'public',
							'action' => 'faq',
						)
					); ?>" class="no-decoration cnt-btn">F.A.Q.</a>
				</div>
			</div>
		</div>
	</article>
	<article class="hero">
		<div class="cnt-heroslider-bg" style="background-image: url('assets/img/quote.jpg');"></div>
		<div class="row">
			<div class="main-container">
				<div class="hero-content-split">
					<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
						<h2 class="herosplit_title">TekLab</h2>
						<p class="herosplit_txt">Soluzioni software per la piccola e media impresa.</p>
						<div class="work-split-btn">
							<a href="#0" class="no-decoration cnt-btn active-btn">Chi siamo</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 mobiles animated fadeInUp">
						<img src="<?php echo $this->baseUrl("assets/img/devices3.png");?>" class="img-responsive" alt="devices" />
					</div>
				</div>
			</div>
		</div>
	</article>
</div>

<!-- Servizi-->
<section id="services">
	<div class="cnt-services-bg">
		<div class="container">
			<h1>Cosa facciamo</h1>
			<p class="title-txt">Soluzioni software complete per ogni esigenza.</p>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered item-container">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
						<i class="pe-7s-call"></i>
						<h2>Linea diretta</h2>
						<p class="items">I nostri clienti possono avere sempre a loro disposizione i nsotri tecnici per ogni problema.</p>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
						<i class="pe-7s-headphones"></i>
						<h2>Formazione e-learnig</h2>
						<p class="items">Soluzioni di e-learning per l'apprendimento delle nostre piattaforme.</p>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 item-services">
						<i class="pe-7s-cloud-upload"></i>
						<h2>Soluzioni cloud</h2>
						<p class="items">Crediamo nel cloud e lo rendiamo disponibile per tutti i nostri prodotti.</p>
					</div>
				</div>

			</div>
			<!-- //.row -->
		</div>
		<!-- //.container-->
	</div>
	<!-- //.cnt-services-bg -->
</section>

<!-- Opinioni -->
<section id="testimonials">
	<div class="cnt-testimonials-bg">
		<div class="container">
			<h1>I nostri feedback</h1>
			<div class="row">
				<div class="col-md-12 col-lg-12 items-testimonials">
					<!-- item testimonial -->
					<div class="col-md-4 col-lg-4 item-testimonial">
						<div class="txt-testimonial">
							<p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree cursus erat et faucibus tempus. Pellentesximus dolor eget erat bibeus. Ut vel nunc vel augue mattis aliquet.</p>
						</div>
						<div class="testimonial">
							<img src="<?php echo $this->baseUrl("assets/img/client-face1.png");?>" alt="" class="img-responsive" width="100" height="100">
							<p class="name">Jane Doe</p>
							<cite>CEO, Impromptu</cite>
						</div>
					</div>
					<!-- //item testimonial -->
					<!-- item testimonial -->
					<div class="col-md-4 col-lg-4 item-testimonial">
						<div class="txt-testimonial">
							<p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree cursus erat et faucibus tempus. Pellentesximus dolor eget erat bibeus. Ut vel nunc vel augue mattis aliquet.</p>
						</div>
						<div class="testimonial">
							<img src="<?php echo $this->baseUrl("assets/img/client-face2.png");?>" alt="" class="img-responsive" width="100" height="100">
							<p class="name">John Doe</p>
							<cite>CTO, CitrusLabs</cite>
						</div>
					</div>
					<!-- //item testimonial -->
					<!-- item testimonial -->
					<div class="col-md-4 col-lg-4 item-testimonial">
						<div class="txt-testimonial">
							<p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree cursus erat et faucibus tempus. Pellentesximus dolor eget erat bibeus. Ut vel nunc vel augue mattis aliquet.</p>
						</div>
						<div class="testimonial">
							<img src="<?php echo $this->baseUrl("assets/img/client-face3.png");?>" alt="" class="img-responsive" width="100" height="100">
							<p class="name">Richard Hendricks</p>
							<cite>CEO, Pied Piper</cite>
						</div>
					</div>
					<!-- //item testimonial -->
				</div>
			</div>
		</div>
		<!-- //.container-->
	</div>
	<!-- //.cnt-testimonials-bg -->
</section>

<!-- Post pubblici del blog-->
<section id="sblog">
	<div class="cnt-sblog-bg">
		<div class="container">
			<h1>Il nostro social network</h1>
			<p class="title-txt">Ecco alcuni degli ultimi post...</p>
			<div class="row-centered">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered cnt-blog-wg">

					<!-- Block 1 -->
					<div class="col-md-4 col-lg-4 cnt-post">
						<div class="fit_image">
							<img src="<?php echo $this->baseUrl("assets/img/quote.jpg");?>" alt="" class="img-responsive">
						</div>
						<h2>How to read to learn and exercise</h2>
						<p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree
						</p>
						<ul class="data-post">
							<li>November 2015</li>
							<li class="separator-post"><i class="fa fa-circle"></i></li>
							<li class="category">Tech Industry</li>
						</ul>
						<a href="<?php echo $this->url(
							array(
								'controller' => 'public',
								'action' => 'login',
							)
						); ?>"><span class="read-more">Read More <i class="fa fa-angle-right"></i></span></a>
					</div>
					<!-- //Block 1 -->

					<!-- Block 2 -->
					<div class="col-md-4 col-lg-4 cnt-post">
						<div class="fit_image">
							<img src="<?php echo $this->baseUrl("assets/img/quote.jpg");?>" alt="" class="img-responsive">
						</div>
						<h2>Timing is Everything for the Eastern Wolf</h2>
						<p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree
						</p>
						<ul class="data-post">
							<li>November 2015</li>
							<li class="separator-post"><i class="fa fa-circle"></i></li>
							<li class="category">Tech Industry</li>
						</ul>
						<a href="<?php echo $this->url(
							array(
								'controller' => 'public',
								'action' => 'login',
							)
						); ?>"><span class="read-more">Read More <i class="fa fa-angle-right"></i></span></a>
					</div>
					<!-- //Block 2 -->

					<!-- Block 3 -->
					<div class="col-md-4 col-lg-4 cnt-post">
						<div class="fit_image">
							<img src="<?php echo $this->baseUrl("assets/img/quote.jpg");?>" alt="" class="img-responsive">
						</div>
						<h2>A look inside amazing offices</h2>
						<p>Lorem ipsolor sit ametetur adipiscing elit. Sed tempus risus vitae ornare laoree
						</p>
						<ul class="data-post">
							<li>November 2015</li>
							<li class="separator-post"><i class="fa fa-circle"></i></li>
							<li class="category">Tech Industry</li>
						</ul>
						<a href="<?php echo $this->url(
							array(
								'controller' => 'public',
								'action' => 'login',
							)
						); ?>"><span class="read-more">Read More <i class="fa fa-angle-right"></i></span></a>
					</div>
					<!-- //Block 3 -->
				</div>
			</div>
			<!-- //.row -->
			<div class="col-lg-12 action-started">
				<a href="<?php echo $this->url(
					array(
						'controller' => 'public',
						'action' => 'login',
					)
				); ?>" class="btn btn-outlined">Read all posts</a>
			</div>
		</div>
		<!-- //.container-->
	</div>
	<!-- //.cnt-sblog-bg -->
</section>

<!-- Get started -->
<section id="started">
	<div class="cnt-started-bg">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<h2>Registrati in pochi minuti e inzia a pubblicare anche tu!</h2>
					<div class="col-lg-12 action-started">
						<a href="<?php echo $this->url(
							array(
								'controller' => 'public',
								'action' => 'register',
							)
						); ?>" class="btn btn-outlined">Registrazione</a>
					</div>
				</div>
			</div>
		</div>
		<!-- //.container-->
	</div>
	<!-- //.cnt-started-bg -->
</section>

</body>
</html>