<body class="black-background">
<div class="logo-login">
</div>

<div class="row">
    <div class="container" id="register">
        <div class="main-login main-center">

            <h2 style="font-size:1.4em; color:#8d9496;">Crea il tuo account</h2>
            <br>
            <?php echo $this->registratiForm; ?>
            <hr class="separator-login">
            <h4>Hai già un account? <span><a href="<?php echo $this->url(
                        array(
                            'controller' => 'public',
                            'action' => 'login',
                        )
                    ); ?>" class="no-decoration">Accedi</a></span></h4>

        </div>

    </div>
    <h2 class="sign-now">Registrandoti accetti i nostri <span><a href="<?php echo $this->url(
                array(
                    'controller' => 'public',
                    'action' => 'terms',
                )
            ); ?>" class="no-decoration">Termini d'utilizzo.</a></span></h2>
</div>

<script type="text/javascript">
    $.validator.setDefaults( {
        submitHandler: function () {
            alert( "submitted!" );
        }
    } );

    $( document ).ready( function () {
        $( "#registrati" ).validate( {
            rules: {
                Nome: "required",
            },
            messages: {
                Nome: "Please enter your firstname",
            },
            errorElement: "em",
            errorPlacement: function ( error, element ) {
                // Add the `help-block` class to the error element
                error.addClass( "help-block" );

                // Add `has-feedback` class to the parent div.form-group
                // in order to add icons to inputs
                element.parents( ".col-sm-5" ).addClass( "has-feedback" );

                if ( element.prop( "type" ) === "checkbox" ) {
                    error.insertAfter( element.parent( "label" ) );
                } else {
                    error.insertAfter( element );
                }

                // Add the span element, if doesn't exists, and apply the icon classes to it.
                if ( !element.next( "span" )[ 0 ] ) {
                    $( "<span class='glyphicon glyphicon-remove form-control-feedback'></span>" ).insertAfter( element );
                }
            },
            success: function ( label, element ) {
                // Add the span element, if doesn't exists, and apply the icon classes to it.
                if ( !$( element ).next( "span" )[ 0 ] ) {
                    $( "<span class='glyphicon glyphicon-ok form-control-feedback'></span>" ).insertAfter( $( element ) );
                }
            },
            highlight: function ( element, errorClass, validClass ) {
                $( element ).parents( ".col-sm-5" ).addClass( "has-error" ).removeClass( "has-success" );
                $( element ).next( "span" ).addClass( "glyphicon-remove" ).removeClass( "glyphicon-ok" );
            },
            unhighlight: function ( element, errorClass, validClass ) {
                $( element ).parents( ".col-sm-5" ).addClass( "has-success" ).removeClass( "has-error" );
                $( element ).next( "span" ).addClass( "glyphicon-ok" ).removeClass( "glyphicon-remove" );
            }
        } );
    } );

</script>
