<html>
<head>
</head>
<body>

<!-- intro -->
<section id="hero" class="hero-about">
	<div id="img-back-about">
		<div class="cnt-header-bg">
			<div class="hero-box">
				<div class="container">
					<div class="hero-text align-center">
						<h1>Termini del servizio</h1>
						<p>Raffaello. Il social network.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- che cos'è raffaello -->
<section id="intro-about">
	<div class="cnt-intro-bg">
		<div class="row">
			<div class="container">
				<h1>A proposito di noi...</h1>
				<h3 class="what-we-do">Che cos'è Raffaello</h3>
				<div class="row-centered">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered intro-about-txt">
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<p>Raffaello è il social network creato da TekLab per i suoi dipendenti. Crediamo nella comunicazione e nella socializzazione ecco perchè abbiamo voluto organizzare uno spazio in cui tutti i nostri professionisti possano scambiarsi idee, opinioni e pensieri liberamente. </p>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<p> Custodiamo le vostre informazioni. Per noi la privacy degli utenti è molto importante. Abbiamo redatto la nostra <a href="#">Normativa sui dati</a> in modo che fornisca indicazioni fondamentali su come usare Raffaello per condividere contenuti con altre persone e su come raccogliamo e possiamo usare i contenuti e le informazioni delle persone.  </p>
						</div>
					</div>
				</div>
			</div>
			<!-- //.container-->
		</div>
	</div>
	<!-- //.cnt-intro-bg -->
</section>

<!-- condizioni del servizio 1 -->
<section id="intro-about">
	<div class="cnt-intro-bg">
		<div class="row">
			<div class="container">
				<h1>Condizioni d'uso</h1>
				<h3 class="what-we-do">Condivisione dei contenuti e delle informazioni</h3>
				<div class="row-centered">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered intro-about-txt">
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<p> L'utente è il proprietario di tutti i contenuti e le informazioni pubblicate su Raffaello e può controllare il modo in cui vengono condivisi mediante le impostazioni di pubblicazione.
								Quando l'utente li elimina, i Contenuti vengono eliminati in modo simile a quando si svuota il cestino del computer. Tuttavia, è possibile che i contenuti rimossi vengano conservati come copie di backup per un determinato periodo di tempo (pur non essendo visibili ad altri).
								Ogni utente può decidere di essere amico di altri inviando una richiesta di amicizia che, a discrezione, può essere accettata o meno.
								Una volta amici questi utenti saranno visibili nella cerchia degli amici.
							</p>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<p> Quando l'utente pubblica contenuti o informazioni usando l'impostazione "Pubblico", concede a tutti, anche alle persone che non sono suoi amici, di accedere e usare tali informazioni e di associarle al suo profilo (ovvero al suo nome e alla sua immagine del profilo).
								<br><br>Ci impegniamo al massimo per fare in modo che Raffaello sia un sito sicuro, ma non possiamo garantirlo. Abbiamo bisogno che gli utenti contribuiscano a tutelare la sicurezza di Raffaello, ovvero che si impegnino ad utilizzare comportamenti accorti nella navigazione. </p>
						</div>
					</div>
				</div>
			</div>
			<!-- //.container-->
		</div>
	</div>
	<!-- //.cnt-intro-bg -->
</section>

<!-- condizioni del servizio 2 -->
<section id="intro-about">
	<div class="cnt-intro-bg">
		<div class="row">
			<div class="container">
				<h3 class="what-we-do">Gestione dell'account</h3>
				<div class="row-centered">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-centered intro-about-txt">
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<p> L'utente amministra in totale libertà il proprio account, condividendo post all'interno del proprio blog, tuttavia in caso di comportamenti non confacenti alla Netiquette della Piattaforma, i gestiori si riservano la facoltà di sospendere ed eliminare l'account dell'utente in questione.
							</p>
						</div>
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
							<p> La registrazione è necessaria per l'accesso alla piattaforma Raffaello; una volta effettuata ogni accesso verrà autorizzato solo dopo aver immesso nome utente (e-mail) e password. Per qualsiasi necessità non esitare a contattarci.
							</p>
						</div>
					</div>
				</div>
			</div>
			<!-- //.container-->
		</div>
	</div>
	<!-- //.cnt-intro-bg -->
</section>

</body>
</html>