<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">
        </div>
    </div>
</section>

<section id="post-blog" class="main-post">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 container-post">
                    <ul class="blog-data">
                        <div class="row" style="text-align: center; margin: auto;>
							<div class=" col-md-12
                        ">
                        <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th class="font-tabella" style="text-align: center">Profili</th>
                                <?php if(count($this->amiciSet)>0): ?>
                                <th class="font-tabella" style="text-align: center">Username</th>
                                <th class="font-tabella" style="text-align: center">Profilo</th>
                                <th class="font-tabella" style="text-align: center">Elimina</th>
                                <?php endif; ?>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <?php if(count($this->amiciSet)==0): ?>
                                <td class="font-tabella-campi">Ops... non hai ancora amici, cerca qualcuno per iniziare!</td>
                                <?php endif; ?>
                                <?php for ($i = 0;
                                $i < count($this->amiciSet);
                                $i++): ?>
                                <td class="font-tabella-campi"
                                    style="text-transform: capitalize"><?php echo $this->amiciSet[$i]['amico']; ?></td>
                                <td class="font-tabella-campi"><?php echo $this->amiciSet[$i]['username']; ?></td>
                                <td style="font-size: 1.2em;">
                                    <a href="<?php echo $this->url(
                                        array(
                                            'controller' => 'user',
                                            'action' => 'profilo',
                                            'user' => $this->amiciSet[$i]['username']
                                        )); ?>">
                                        <button type="button"
                                                class="btn btn-lg btn-primary btn-block btn-signin button-blue-nic"
                                                style="width: 30pt">
											<span>
                                            <i class="fa fa-arrow-right"></i>
                                        </span>
                                        </button>
                                    </a>
                                </td>
                                <td style="font-size: 1.2em;">
                                    <a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'eliminaprofilo',
                                        'user' => $this->amiciSet[$i]['idamico']
                                    ));
                                    ?>">
                                        <button type="button"
                                                class="btn btn-lg btn-primary btn-block btn-signin button-red-nic"
                                                style="width: 30pt">
											<span>
                                            <i class="fa fa-times-circle"></i>
                                        </span>

                                        </button>
                                    </a>
                                </td>
                            </tr>
                            <?php endfor; ?>
                            </tbody>
                        </table>
                        <div class="row" style="margin-top: 10px">
                            <div class="col-md-5 col-sm-5 col-lg-5"></div>
                            <div class="col-lg-12 action-started">
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'index'));
                                ?>" class="btn btn-outlined">Indietro</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>