<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">
        </div>
    </div>
</section>

<section id="post-blog" class="main-post">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 container-post">
                    <ul class="blog-data">
                        <div class="row" style="text-align: center; margin: auto;>
							<div class=">
                            <h2 style="margin-bottom: 20pt; text-align: left"> Risultato ricerca </h2>
                            <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                                   width="100%">
                                <thead>
                                <tr>
                                    <?php if (count($this->amiciSet) > 0): ?>
                                        <th class="font-tabella" style="text-align: center">Nome e Cognome</th>
                                        <th class="font-tabella" style="text-align: center">Vai al profilo</th>
                                    <?php else: ?>
                                        <th class="font-tabella" style="text-align: center">Nome e Cognome</th>
                                    <?php endif; ?>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <?php if (count($this->amiciSet) == 0): ?>
                                        <td class="font-tabella-campi" style="font-size: 15pt">Ops... la ricerca non ha
                                            prodotto risultati! Verifica i dati inseriti...
                                        </td>
                                    <?php endif; ?>
                                    <?php foreach ($this->amiciSet as $amici): ?>
                                    <td class="font-tabella-campi"
                                        style="text-transform: capitalize"><?php echo $amici['nomecompleto']; ?></td>
                                    <td style="font-size: 1.2em;">
                                        <a href="<?php echo $this->url(
                                            array(
                                                'controller' => 'user',
                                                'action' => 'profilo',
                                                'user' => $amici['username'],
                                                'privacy' => $amici['privacy']
                                            )); ?>">
                                            <button type="button"
                                                    class="btn btn-lg btn-primary btn-block btn-signin button-blue-nic"
                                                    style="width: 30pt">
											<span>
                                            <i class="fa fa-arrow-right"></i>
                                        </span>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                </div>
            </div>
        </div>
</section>