<html>
<head>
</head>
<body>

<body class="black-background">

<div class="logo-login">
</div>

<div class="row">

    <div class="container" id="register">

        <div class="hero-text align-center" style="text-align: center">
            <h1>Conferma eliminazione</h1>
        </div>

        <div class="main-login main-center">
            <h2 style="font-size:1.6em; color: #761c19;">Stai eliminando il tuo blog "<?php echo $this->titolo; ?>"</h2>
            <br>
            <h2 style="font-size:1.4em; color: #0a151e;">Confermi l'eliminazione?</h2>
            <br>
            <br>

            <div class="col-lg-12 action-started" align="center" style="margin-bottom: auto; margin-top: auto">
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <a href="<?php echo $this->url(array(
                        'controller' => 'user',
                        'action' => 'eliminablogpost'));
                    ?>" class="btn btn-lg btn-primary btn-block btn-signin button-green-nic"
                       style="height: 20px; width: 100px; text-align: center; vertical-align: middle;">Si</a>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <a href="<?php echo $this->url(array(
                        'controller' => 'user',
                        'action' => 'gestioneblog'),
                        null, true);
                    ?>" class="btn btn-lg btn-primary btn-block btn-signin button-green-nic"
                       style="height: 20px; width: 100px; text-align: center; vertical-align: middle;">No</a>
                </div>
            </div>


        </div>
    </div>
</div>

<hr class="separator-login">


</body>