<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">

        </div>
    </div>
    </div>
</section>

<section id="post-blog" class="blog-right-sidebar">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <section id="faq-2">
                        <div class="cnt-faq-bg">
                            <div class="container">
                                <h1>Per iniziare, seleziona un blog...</h1>
                                <div class="row-centered">
                                    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-centered">
                                        <div class="panel-group" id="accordion">

                                            <?php foreach ($this->blogSet as $blog): ?>
                                                <div class="panel panel-default">
                                                    <div class="panel-heading">
                                                        <a class="accordion-toggle collapsed" data-toggle="collapse"
                                                           data-parent="#accordion" href="<?php echo $this->url(
                                                            array(
                                                                'controller' => 'user',
                                                                'action' => 'visualizzablog',
                                                                'blog' => $blog->id_blog
                                                            )
                                                        ); ?>">
                                                            <h4 class="panel-title"
                                                                style="text-transform: capitalize"><a
                                                                    href="<?php echo $this->url(
                                                                        array(
                                                                            'controller' => 'user',
                                                                            'action' => 'visualizzablog',
                                                                            'blog' => $blog->id_blog
                                                                        )
                                                                    ); ?>"><?php echo $blog->titolo; ?></a></h4>
                                                        </a>
                                                    </div>
                                                </div>
                                            <?php endforeach; ?>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <div class="col-lg-12 action-started" style="margin-bottom: auto; margin-top: auto">
                        <a href="<?php echo $this->url(
                            array(
                                'controller' => 'user',
                                'action' => 'inserimentoprimoblog',
                                'verifica' => '1'
                            )
                        ); ?>" class="btn btn-outlined">Crea un nuovo blog</a>
                    </div>


                </div>

                <div class="col-lg-4 container-right-sidebar">
                    <br>
                    <br>
                    <span class="dotted-line"></span>
                    <div class="col-lg-12 cnt-form-search">
                        <form method="post" class="searchbox-container" action="<?php echo $this->url(
                            array(
                                'controller' => 'user',
                                'action' => 'cerca',
                            )); ?>">
                            <input type="search" class="searchbox" name="search" autocomplete="off"
                                   placeholder="Cerca..."/>
                            <button type="submit" class="searchbutton fa fa-search"></button>
                        </form>
                    </div>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 cnt-about-us">
                        <h3 style="text-transform: capitalize">Ciao, <?php echo $this->nome ?>!</h3>
                        <hr class="title-sidebar"/>

                        <!-- TABELLA RICHIESTE DI AMICIZIA -->
                        <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th class="font-tabella" style="text-align: center">Richieste di Amicizia</th>
                                <?php if (count($this->amiciSet) != 0): ?>
                                    <th class="font-tabella" style="text-align: center">Accetta</th>
                                    <th class="font-tabella" style="text-align: center">Rifiuta</th>
                                <?php endif; ?>
                            </tr>
                            </thead>

                            <tbody>
                            <tr>
                                <?php for ($i = 0;
                                $i < count($this->amiciSet);
                                $i++): ?>
                                <td class="font-tabella-campi"
                                    style="text-align: center; text-transform: capitalize"><?php echo $this->amiciSet[$i]['richiedente']; ?></td>
                                <td style="font-size: 1.2em; text-align: center">
                                    <a href="<?php echo $this->url(
                                        array(
                                            'controller' => 'user',
                                            'action' => 'amicipost',
                                            'idamici' => $this->amiciSet[$i]['id_amici'],
                                            'azione' => 'accepted'
                                        )); ?>">
                                        <span>
                                            <i class="fa fa-check-square" style="color: #21DC7F"></i>
                                        </span>
                                    </a>
                                </td>
                                <td style="font-size: 1.2em; text-align: center">
                                    <a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'amicipost',
                                        'idamici' => $this->amiciSet[$i]['id_amici'],
                                        'azione' => 'refused'
                                    ));
                                    ?>">
                                        <span>
                                            <i class="fa fa-times-circle" style="color: #761c19"></i>
                                        </span>
                                    </a>
                                </td>
                            </tr>
                            <?php endfor; ?>
                            <?php if ($i == 0): ?>
                                <td class="font-tabella-campi" style="text-align: center">Non hai nessuna nuova
                                    richiesta!
                                </td>
                                </tr>
                            <?php endif; ?>


                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-5 col-sm-5 col-lg-5"></div>
                            <div class="col-lg-12 action-started">
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'amici'),
                                    null, true);
                                ?>" class="btn btn-outlined">Tutti gli amici <span>
                                            <i class="fa fa-arrow-right"></i>
                                        </span></a>
                            </div>
                        </div>

                        <!-- FINE TABELLA -->
                    </div>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 popular-posts">
                        <h3>Ultimi Post</h3>
                        <hr class="title-sidebar"/>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                    </div>

                    <span class="dotted-line"></span>
                    <div class="col-lg-12 archives">
                        <h3>I tuoi Blog</h3>
                        <hr class="title-sidebar"/>
                        <div class="cnt-sidebar">
                            <?php foreach ($this->blogSet as $blog): ?>
                                <div class="archive-first"><a href="#"><?php echo $blog->titolo; ?></a><span><i
                                            class="fa fa-plus"></i></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <span class="dotted-line"></span>

                </div>
            </div>
            <!-- //.row -->
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-post-bg -->
</section>