<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">

        </div>
    </div>
    </div>
</section>

<section id="post-blog" class="blog-right-sidebar">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <?php if ($this->valPost): ?>
                        <div class="col-lg-12 container-post">
                            <div class="featured-image">
                                <img src="http://eship.dyson.cornell.edu/wp-eship/wp-content/uploads/idea-lightbulb.jpg"
                                     class="img-responsive" alt="">
                            </div>
                            <h2>Ops...</h2>
                            <p>Non hai ancora inserito alcun post, inizia ora!</p>
                            <br>
                            <br>
                            <br>
                            <div class="col-lg-12 action-started">
                                <a href="blog-single-post.html" class="btn btn-outlined">CREA UN POST</a>
                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if (!$this->valPost): ?>
                        <?php foreach ($this->postSet as $post): ?>
                            <div class="col-lg-12 container-post">
                                <!-- .featured-image -->
                                <div class="featured-image">
                                    <img src="assets/img/workspace.jpg" class="img-responsive" alt="">
                                    <div class="data-post-main">
                                        <ul class="blog-data">
                                            <li><i class="pe-7s-date"></i> <?php echo $post->data; ?></li>
                                            <li><i class="pe-7s-comment"></i> <?php echo $this->numcom ?> comment<?php if ($this->numcom == 1){
                                                    echo 'o';
                                                } else {echo 'i';} ?></li>
                                        </ul>
                                    </div>
                                </div>
                                <!-- //.featured-image -->
                                <h2> <?php echo $post->titolo; ?> </h2>
                                <p> <?php echo $post->contenuto; ?></p>
                                <div class="col-lg-12 action-started" style="margin-bottom: 30px; margin-top: 80px">
                                    <a href="#" class="btn btn-outlined">Continua a leggere</a>
                                </div>
                            </div>

                        <?php endforeach; ?>
                        <?php endif; ?>

                </div>

                <div class="col-lg-4 container-right-sidebar">
                    <br>
                    <br>
                    <span class="dotted-line"></span>
                    <div class="col-lg-12 cnt-form-search">
                        <form class="searchbox-container" action="http://citruslabsthemes.com/themes/impromptu/.">
                            <input type="search" class="searchbox" name="search" autocomplete="off"
                                   placeholder="Cerca..."/>
                            <button type="submit" class="searchbutton fa fa-search"></button>
                        </form>
                    </div>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 cnt-about-us">
                        <h3>Ciao, <?php echo $this->nome ?>!</h3>
                        <hr class="title-sidebar"/>
                        <p> richieste di amicizia </p>
                    </div>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 popular-posts">
                        <h3>Ultimi Post</h3>
                        <hr class="title-sidebar"/>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                    </div>

                    <span class="dotted-line"></span>
                    <div class="col-lg-12 archives">
                        <h3>I tuoi Blog</h3>
                        <hr class="title-sidebar"/>
                        <div class="cnt-sidebar">
                            <?php foreach ($this->blogSet as $blog): ?>
                                <div class="archive-first"><a href="#"><?php echo $blog->titolo; ?></a><span><i
                                            class="fa fa-plus"></i></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <span class="dotted-line"></span>

                </div>
            </div>
            <!-- //.row -->
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-post-bg -->
</section>