<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">

        </div>
    </div>
    </div>
</section>

<section id="post-blog" class="blog-right-sidebar">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <?php if ($this->valPost): ?>
                        <div class="col-lg-12 container-post">
                            <div class="featured-image">
                                <img src="http://eship.dyson.cornell.edu/wp-eship/wp-content/uploads/idea-lightbulb.jpg"
                                     class="img-responsive" alt="">
                            </div>
                            <h2>Ops...</h2>
                            <p>Non hai ancora inserito alcun post, inizia ora!</p>
                            <br>
                            <br>
                            <br>
                            <div class="col-lg-12 action-started">
                                <a href="blog-single-post.html" class="btn btn-outlined">CREA UN POST</a>
                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if (!$this->valPost): ?>
                        <section id="faq-2">
                            <div class="cnt-faq-bg">
                                <div class="container">
                                    <h1>Per iniziare, seleziona un blog...</h1>
                                    <div class="row-centered">
                                        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-centered">
                                            <div class="panel-group" id="accordion">

                                                    <?php foreach ($this->blogSet as $blog): ?>
                                                    <div class="panel panel-default">
                                                        <div class="panel-heading">
                                                            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#">
                                                                <h4 class="panel-title"><?php echo $blog->titolo; ?></h4>
                                                            </a>
                                                        </div>
                                                    </div>
                                                    <?php endforeach; ?>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                        <div class="col-lg-12 action-started" style="margin-bottom: auto; margin-top: auto">
                            <div class="col-md-6 col-sm-6 col-xs-12" style="margin-bottom: 10px">
                                <a href="#" class="btn btn-outlined">Crea un nuovo post</a>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">

                                <a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'user',
                                        'action' => 'inserimentoprimoblog',
                                        'verifica' => '1'
                                    )
                                ); ?>" class="btn btn-outlined">Crea un nuovo blog</a>
                            </div>
                        </div>
                    <?php endif; ?>

                </div>

                <div class="col-lg-4 container-right-sidebar">
                    <br>
                    <br>
                    <span class="dotted-line"></span>
                    <div class="col-lg-12 cnt-form-search">
                        <form class="searchbox-container" action="http://citruslabsthemes.com/themes/impromptu/.">
                            <input type="search" class="searchbox" name="search" autocomplete="off"
                                   placeholder="Cerca..."/>
                            <button type="submit" class="searchbutton fa fa-search"></button>
                        </form>
                    </div>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 cnt-about-us">
                        <h3>Ciao, <?php echo $this->nome ?>!</h3>
                        <hr class="title-sidebar"/>
                        <p> richieste di amicizia </p>
                    </div>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 popular-posts">
                        <h3>Ultimi Post</h3>
                        <hr class="title-sidebar"/>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                    </div>

                    <span class="dotted-line"></span>
                    <div class="col-lg-12 archives">
                        <h3>I tuoi Blog</h3>
                        <hr class="title-sidebar"/>
                        <div class="cnt-sidebar">
                            <?php foreach ($this->blogSet as $blog): ?>
                                <div class="archive-first"><a href="#"><?php echo $blog->titolo; ?></a><span><i
                                            class="fa fa-plus"></i></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <span class="dotted-line"></span>

                </div>
            </div>
            <!-- //.row -->
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-post-bg -->
</section>