<html>
<head>
</head>
<body>

<body class="black-background">
<div class="logo-login">
</div>

<div class="row">

    <div class="container" id="register">

        <?php if ($this->verifica != 1): ?>
            <div class="hero-text align-center" style="text-align: center">
                <h1 style="text-transform: capitalize">Ciao <?php echo $this->nome; ?>, </h1>
                <h1>per iniziare inserisci il tuo primo blog!</h1>
            </div>
        <?php else: ?>
            <div class="hero-text align-center" style="text-align: center">
                <h1>Crea un nuovo blog...</h1>
            </div>
        <?php endif; ?>

        <div class="main-login main-center">
            <br>
            <?php echo $this->nuovoblogForm; ?>
            <hr class="separator-login">
        </div>

    </div>

</div>

<script type="text/javascript">
    $.validator.setDefaults({
        submitHandler: function () {
            $("#nuovoblog").submit();
        }
    });

    $(document).ready(function () {
        $("#nuovoblog").validate({
            rules: {
                titolo: {
                    required: true,
                    minlength: 3
                },
                descrizione: {
                    minlength: 3
                },
                tema: {
                    required: true,
                    minlength: 3
                }
            },
            messages: {
                titolo: {
                    required: "Il campo titolo non può essere vuoto.",
                    minlength: "Il titolo deve essere almeno di 3 caratteri."
                },
                descrizione: {
                    minlength: "La descrizione deve avere almeno 4 caratteri."
                },
                tema: {
                    required: "Il campo tema non può essere vuoto.",
                    minlength: "Il tema deve avere almeno 3 caratteri."
                }
            },
            errorElement: "em",
            errorPlacement: function (error, element) {
                // Add the `help-block` class to the error element
                error.addClass("help-block");

                // Add `has-feedback` class to the parent div.form-group
                // in order to add icons to inputs
                element.parents(".col-sm-5").addClass("has-feedback");

                if (element.prop("type") === "checkbox") {
                    error.insertAfter(element.parent("label"));
                } else {
                    error.insertAfter(element);
                }
            },
            success: function (label, element) {

            },
            highlight: function (element, errorClass, validClass) {
                $(element).parents(".col-sm-5").addClass("has-error").removeClass("has-success");
                $(element).attr("style", "border: 2px solid red");
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).parents(".col-sm-5").addClass("has-success").removeClass("has-error");
                $(element).attr("style", "2px solid #E3E7E9");
            }
        });
    });

</script>