<html>
<head>
</head>
<body>

<body class="black-background">

<div class="logo-login">
</div>

<div class="row">

    <div class="container" id="register">

        <?php if ($this->verifica != 1): ?>
            <div class="hero-text align-center" style="text-align: center">
                <h1>Ciao <?php echo $this->nome; ?>, </h1>
                <h1>per iniziare inserisci il tuo primo blog!</h1>
            </div>
        <?php else: ?>
            <div class="hero-text align-center" style="text-align: center">
                <h1>Crea un nuovo blog...</h1>
            </div>
        <?php endif; ?>

        <div class="main-login main-center">
            <br>
            <?php echo $this->nuovoblogForm; ?>
            <hr class="separator-login">
        </div>

    </div>

</div>


</body>