<html>
<head>
</head>
<body>

<body class="black-background">
<div class="logo-login">
</div>

<div class="row">
    <div class="container" id="register">

        <div class="main-login main-center">
            <h2 style="font-size:1.4em; color:#8d9496; text-transform: capitalize">
                Modifica: <?php echo $this->utentiSet['nome']; ?> <?php echo $this->utentiSet['cognome']; ?> </h2>
            <br>
            <?php echo $this->formUtente; ?>
        </div>

    </div>
</div>
</div>

</body>

<script type="text/javascript">
    $.validator.setDefaults({
        submitHandler: function () {
            $("#datiutente").submit();
        }
    });

    $(document).ready(function () {
        $("#datiutente").validate({
            rules: {
                nome: "required",
                cognome: "required",
                nascita: {
                    required: true,
                    date: true
                },
                email: {
                    required: true,
                    email: true
                },
                username: {
                    required: true,
                    minlength: 3
                },
                password: {
                    minlength: 4
                },
                password_confirm: {
                    minlength: 4,
                    equalTo: "#password"
                },
                telefono: {
                    required: true,
                    digits: true
                },
                descrizione: {
                    required: true,
                    minlength: 3
                }
            },
            messages: {
                nome: "Inserisci il tuo nome.",
                cognome: "Inserisci il tuo cognome.",
                nascita: {
                    required: "Il campo data di nascita non può essere vuoto.",
                    date: "Inserisci una data corretta."
                },
                email: {
                    required: "Il campo email non può essere vuoto.",
                    email: "Inserisci una email valida."
                },
                username: {
                    required: "Il campo username non può essere vuoto.",
                    minlength: "L'username deve essere almeno di 3 caratteri."
                },
                password: {
                    minlength: "La password deve avere almeno 4 caratteri."
                },
                password_confirm: {
                    minlength: "La password deve avere almeno 4 caratteri.",
                    equalTo: "Le passoword inserite non coincidono."
                },
                telefono: {
                    required: "Il campo telefono non può essere vuoto.",
                    digits: "Il campo telefono deve contenere soltanto caratteri numerici."
                },
                descrizione: {
                    required: "Il campo descrizione non può essere vuoto.",
                    minlength: "La password deve avere almeno 3 caratteri."
                }
            },
            errorElement: "em",
            errorPlacement: function (error, element) {
                // Add the `help-block` class to the error element
                error.addClass("help-block");

                // Add `has-feedback` class to the parent div.form-group
                // in order to add icons to inputs
                element.parents(".col-sm-5").addClass("has-feedback");

                if (element.prop("type") === "checkbox") {
                    error.insertAfter(element.parent("label"));
                } else {
                    error.insertAfter(element);
                }
            },
            success: function (label, element) {

            },
            highlight: function (element, errorClass, validClass) {
                $(element).parents(".col-sm-5").addClass("has-error").removeClass("has-success");
                $(element).attr("style", "border: 2px solid red");
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).parents(".col-sm-5").addClass("has-success").removeClass("has-error");
                $(element).attr("style", "2px solid #E3E7E9");
            }
        });
    });

</script>