<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">
        </div>
    </div>
</section>

<section id="faq-2">
    <div class="cnt-faq-bg">
        <div class="container">
            <h1>Impostazioni privacy</h1>
            <div class="row-centered">
                <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-centered">
                    <div class="panel-group" id="accordion">

                        <!-- Scelta multipla tra due Impostazioni -->
                        <div class="row-centered">
                            <h2 style="text-align: center ;color: #0a151e; font-family: 'Open Sans',sans-serif; font-weight: 300; font-size: 1.4rem; margin-top: 10px; margin-bottom: 20pt; width: 100%;">
                                Al momento la tua privacy è impostata
                                su: <?php if ($this->privacy == 0) echo "Pubblico"; else echo "Privato"; ?></h2>
                            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-centered">
                                <div class="panel-group" id="accordion" style="margin-top: auto">
                                    <div class="panel panel-default" style="margin-top: 2pt">
                                        <div class="panel-heading">
                                            <a class="accordion-toggle collapsed" data-toggle="collapse"
                                               data-parent="#accordion" href="<?php echo $this->url(
                                                array(
                                                    'controller' => 'user',
                                                    'action' => 'modificaprivacypost',
                                                    'privacy' => 0
                                                )
                                            ); ?>">
                                                <h4 class="panel-title"
                                                    style="text-transform: capitalize"><a
                                                        href="<?php echo $this->url(
                                                            array(
                                                                'controller' => 'user',
                                                                'action' => 'modificaprivacypost',
                                                                'privacy' => 0
                                                            )
                                                        ); ?>">PROFILO PUBBLICO</a></h4>
                                            </a>
                                        </div>
                                    </div>
                                    <p style="color: #0a151e; font-family: 'Open Sans',sans-serif; font-weight: 300; font-size: 1.4rem; margin-top: 10px; margin-bottom: 10pt; width: 100%;">
                                        Il profilo pubblico viene impostato di default dal sistema; in questo modo
                                        risulterai visibile a tutti gli utenti della piattaforma, che potranno cercarti
                                        e trovare le tue informazioni personali.</p>

                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <a class="accordion-toggle collapsed" data-toggle="collapse"
                                               data-parent="#accordion" href="<?php echo $this->url(
                                                array(
                                                    'controller' => 'user',
                                                    'action' => 'modificaprivacypost',
                                                    'privacy' => 1
                                                )
                                            ); ?>">
                                                <h4 class="panel-title"
                                                    style="text-transform: capitalize"><a
                                                        href="<?php echo $this->url(
                                                            array(
                                                                'controller' => 'user',
                                                                'action' => 'modificaprivacypost',
                                                                'privacy' => 1
                                                            )
                                                        ); ?>">PROFILO PRIVATO</a></h4>
                                            </a>
                                        </div>
                                    </div>
                                    <p style="color: #0a151e; font-family: 'Open Sans',sans-serif; font-weight: 300; font-size: 1.4rem; margin-top: 10px; margin-bottom: 10pt; width: 100%;">
                                        Scegliendo il profilo privato mostrerai agli utenti che non sono tuoi amici solo
                                        il tuo nome e cognome.</p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
</section>
