<html>
<head>
</head>
<body>

<body class="black-background">
<div class="logo-login">
</div>

<div class="row">
    <div class="container" id="register">

        <div class="hero-text align-center" style="text-align: center">
            <h1>Crea un nuovo post...</h1>
        </div>

        <div class="main-login main-center">
            <br>
            <?php echo $this->nuovopostForm; ?>
            <hr class="separator-login">
        </div>
    </div>
</div>

<script type="text/javascript">
    $.validator.setDefaults({
        submitHandler: function () {
            $("#nuovopost").submit();
        }
    });

    $(document).ready(function () {
        $("#nuovopost").validate({
            rules: {
                titolo: {
                    required: true,
                    minlength: 3
                },
                contenuto: "required"
            },
            messages: {
                titolo: {
                    required: "Il campo titolo non può essere vuoto.",
                    minlength: "Il titolo deve essere almeno di 3 caratteri."
                },
                contenuto: "Il campo contenuto non può essere vuoto."
            }
        });
    });

</script>