<html>
<head>
</head>
<body>

<body class="black-background">
<div class="logo-login">
</div>

<div class="row">
    <div class="container" id="register">

        <div class="hero-text align-center" style="text-align: center">
            <h1>Crea un nuovo post...</h1>
        </div>

        <div class="main-login main-center">
            <br>
            <?php echo $this->nuovopostForm; ?>
            <hr class="separator-login">
        </div>
    </div>
</div>

</body>