<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">
        </div>
    </div>
</section>


<section id="post-blog" class="main-post">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 container-post">
                    <ul class="blog-data">
                        <div class="row" style="text-align: center; margin: auto;>
							<div class=" col-md-12
                        ">
                        <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th class="font-tabella" style="text-align: center">Notifiche</th>
                            </tr>
                            </thead>

                            <tbody>
                            <tr>

                                <?php for ($i = 0;
                                $i < count($this->notificaSet);
                                $i++): ?>
                                <?php if ($this->notificaSet[$i]['tipo'] == 0): ?>
                                    <?php if ($this->notificaSet{$i}['esistenzablog'] == false || $this->notificaSet{$i}['esistenzapost'] == false): ?>
                                        <!-- DO NOTHING -->
                                    <?php else: ?>
                                        <td class="font-tabella-campi">
                                            <a href="<?php echo $this->url(array(
                                                'controller' => 'user',
                                                'action' => 'profilo',
                                                'user' => $this->notificaSet[$i]['user']
                                            ));
                                            ?>"><?php echo $this->notificaSet[$i]['mittente']; ?></a> ha pubblicato un
                                            nuovo
                                            post
                                            in <a href="<?php echo $this->url(array(
                                                'controller' => 'user',
                                                'action' => 'visualizzablog',
                                                'blog' => $this->notificaSet[$i]['idblog']
                                            ));
                                            ?>">"<?php echo $this->notificaSet[$i]['blog']; ?>"</a>
                                            il <?php echo $this->notificaSet[$i]['data']; ?>.
                                        </td>
                                    <?php endif; ?>
                                <?php elseif ($this->notificaSet[$i]['tipo'] == 1): ?>
                                    <td class="font-tabella-campi">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'profilo',
                                            'user' => $this->notificaSet[$i]['user']
                                        ));
                                        ?>"><?php echo $this->notificaSet[$i]['mittente']; ?></a> ti ha eliminato dai
                                        suoi
                                        amici.
                                    </td>
                                <?php elseif ($this->notificaSet[$i]['tipo'] == 2): ?>
                                    <td class="font-tabella-campi">
                                        Staff ha appena eliminato un tuo
                                        post dal blog "<?php echo $this->notificaSet[$i]['nome']; ?>"
                                        causa <?php echo $this->notificaSet[$i]['motivazione']; ?>.
                                    </td>
                                <?php elseif ($this->notificaSet[$i]['tipo'] == 3): ?>
                                    <td class="font-tabella-campi">
                                        Staff ha appena eliminato il tuo
                                        blog "<?php echo $this->notificaSet[$i]['blog']; ?>"
                                        causa <?php echo $this->notificaSet[$i]['motivazione']; ?>.
                                    </td>
                                <?php else: ?>
                                    <td class="font-tabella-campi">
                                        Ops... c'è qualcosa che non va in questa notifica. Contatta l'amministratore del
                                        sito per aiuto!
                                    </td>
                                <?php endif; ?>
                            </tr>
                            <?php endfor; ?>
                            </tbody>
                        </table>
                </div>
            </div>
        </div>
    </div>
</section>