<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">

        </div>
    </div>
    </div>
</section>

<section id="post-blog" class="blog-right-sidebar">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <!-- INIZIO POST -->
                    <div class="col-lg-12 container-post">
                        <!-- .featured-image -->
                        <div class="row">
                            <div class="col-md-5 col-sm-5 col-lg-5">
                                <h2 style="font-size: 40pt; width: auto; margin-top: auto; color: #21DC7F;"><?php echo $this->blogSet['titolo']; ?></h2>
                                <a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'user',
                                        'action' => 'nuovopost',
                                        'user' => $this->utenteCorrente
                                    )
                                ); ?>" class="btn btn-outlined" style="margin-top: 5%; margin-bottom: 20pt;">Nuovo Post</a>
                            </div>
                        </div>
                        <?php
                        for ($i = 0; $i < count($this->postSet); $i++): ?>
                            <div class="featured-image">
                                <img src="http://eship.dyson.cornell.edu/wp-eship/wp-content/uploads/idea-lightbulb.jpg"
                                     class="img-responsive" alt="">
                                <div class="data-post-main">
                                    <ul class="blog-data">
                                        <li><i class="pe-7s-date"></i> <?php echo $this->postSet[$i]['data']; ?></li>
                                        <li><i class="pe-7s-comment"></i>Da: <a href="<?php echo $this->url(
                                                array(
                                                    'controller' => 'user',
                                                    'action' => 'profilo',
                                                    'user' => $this->postSet[$i]['id_utente']
                                                ),
                                                null, true
                                            ); ?>"><?php echo $this->postSet[$i]['nome_utente']; ?></a></li>
                                    </ul>
                                </div>
                            </div>
                            <!-- //.featured-image -->
                            <h2><?php echo $this->postSet[$i]['titolo']; ?></h2>
                            <p style="margin-bottom: 20%"><?php echo $this->postSet[$i]['contenuto']; ?></p>
                        <?php endfor; ?>

                        <?php if ($this->valPost == 0):
                            echo $this->valPost;
                            ?>
                            <div class="col-lg-12 container-post">
                                <div class="featured-image">
                                    <img
                                        src="http://eship.dyson.cornell.edu/wp-eship/wp-content/uploads/idea-lightbulb.jpg"
                                        class="img-responsive" alt="">
                                </div>
                                <h2>Ops...</h2>
                                <p>Non hai ancora inserito alcun post, inizia ora!</p>
                                <br>
                                <br>
                                <br>
                                <div class="col-lg-12 action-started">
                                    <a href="<?php echo $this->url(
                                        array(
                                            'controller' => 'user',
                                            'action' => 'nuovopost'
                                        )
                                    ); ?>" class="btn btn-outlined">CREA UN POST</a>
                                </div>
                            </div>
                        <?php endif; ?>

                    </div>
                    <!-- FINE POST -->
                </div>

                <div class="col-lg-4 container-right-sidebar">
                    <br>
                    <br>
                    <span class="dotted-line"></span>
                    <div class="col-lg-12 cnt-form-search">
                        <form class="searchbox-container" action="http://citruslabsthemes.com/themes/impromptu/.">
                            <input type="search" class="searchbox" name="search" autocomplete="off"
                                   placeholder="Cerca..."/>
                            <button type="submit" class="searchbutton fa fa-search"></button>
                        </form>
                    </div>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 cnt-about-us">
                        <h3>Ciao, <?php echo $this->nome ?>!</h3>
                        <hr class="title-sidebar"/>
                        <!-- TABELLA RICHIESTE DI AMICIZIA -->
                        <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th class="font-tabella" style="text-align: center">Nuovi Amici</th>
                                <?php if (count($this->amiciSet) != 0): ?>
                                    <th class="font-tabella" style="text-align: center">Accetta</th>
                                    <th class="font-tabella" style="text-align: center">Rifiuta</th>
                                <?php endif ?>
                            </tr>
                            </thead>

                            <tbody>
                            <tr>
                                <?php for ($i = 0;
                                $i < count($this->amiciSet);
                                $i++): ?>
                                <td class="font-tabella-campi"
                                    style="text-align: center"><?php echo $this->amiciSet[$i]['richiedente']; ?></td>
                                <td style="font-size: 1.2em; text-align: center">
                                    <a href="<?php echo $this->url(
                                        array(
                                            'controller' => 'user',
                                            'action' => 'amicipost',
                                            'idamici' => $this->amiciSet[$i]['id_amici'],
                                            'azione' => 'accepted'
                                        )); ?>">
                                        <span>
                                            <i class="fa fa-check-square" style="color: #21DC7F"></i>
                                        </span>
                                    </a>
                                </td>
                                <td style="font-size: 1.2em; text-align: center">
                                    <a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'amicipost',
                                        'idamici' => $this->amiciSet[$i]['id_amici'],
                                        'azione' => 'refused'
                                    )); ?>">
                                        <span>
                                            <i class="fa fa-times-circle" style="color: #761c19"></i>
                                        </span>
                                    </a>
                                </td>
                            </tr>
                            <?php endfor; ?>
                            <?php if ($i == 0): ?>
                                <td class="font-tabella-campi" style="text-align: center">Non hai nessuna nuova
                                    richiesta!
                                </td>
                                </tr>
                            <?php endif; ?>

                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-5 col-sm-5 col-lg-5"></div>
                            <div class="col-lg-12 action-started">
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'amici'));
                                ?>" class="btn btn-outlined">Tutti gli amici <span>
                                            <i class="fa fa-arrow-right"></i>
                                        </span></a>
                            </div>
                        </div>
                        <!-- FINE TABELLA -->
                    </div>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 popular-posts">
                        <h3>Ultimi Post</h3>
                        <hr class="title-sidebar"/>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-lg-12 top_post_right">
                            <h2>This amazing Blog Post Headline</h2>
                            <p>Home to celebrities, rappers, musicians, and Al Capone's hideaway, Miami is best known
                                for...a really good time</p>
                            <ul class="data-post-right">
                                <li><span class="icon-process">Posted by</span> Herbert Gonzalez</li>
                                <li>|&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-bubble icon-process"></i> 1 reply</li>
                            </ul>
                        </div>
                    </div>

                    <span class="dotted-line"></span>
                    <div class="col-lg-12 archives">
                        <h3>I tuoi Blog</h3>
                        <hr class="title-sidebar"/>
                        <div class="cnt-sidebar">
                            <?php foreach ($this->blogSet as $blog): ?>
                                <div class="archive-first"><a href="#"><?php echo $blog->titolo; ?></a><span><i
                                            class="fa fa-plus"></i></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <span class="dotted-line"></span>

                </div>
            </div>
            <!-- //.row -->
        </div>
        <!-- //.container-->
    </div>
    <!-- //.cnt-post-bg -->
</section>