<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">

        </div>
    </div>
    </div>
</section>

<section id="post-blog" class="blog-right-sidebar">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                    <!-- INIZIO POST -->
                    <div class="col-lg-12 container-post">
                        <!-- .featured-image -->
                        <div class="row">
                            <div class="col-md-5 col-sm-5 col-lg-5">
                                <h2 style="font-size: 40pt; width: auto; margin-top: auto; color: #21DC7F;"><?php echo $this->blogSet['titolo']; ?></h2>
                                <a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'user',
                                        'action' => 'nuovopost',
                                        'user' => $this->utenteCorrente
                                    )
                                ); ?>" class="btn btn-outlined" style="margin-top: 5%; margin-bottom: 20pt;">Nuovo
                                    Post</a>
                            </div>
                        </div>
                        <?php
                        foreach ($this->postSet as $post): ?>
                            <div class="featured-image">
                                <img src="<?php echo $this->baseUrl("image/post/".$post['image']); ?>"
                                     class="img-responsive" alt="">
                                <div class="data-post-main">
                                    <ul class="blog-data">
                                        <li><i class="pe-7s-date"></i> <?php

                                            echo $post['data']; ?></li>
                                        <li><i class="pe-7s-comment"></i>Da: <a href="<?php echo $this->url(
                                                array(
                                                    'controller' => 'user',
                                                    'action' => 'profilo',
                                                    'user' => $post['username']
                                                ),
                                                null, true
                                            ); ?>"><?php echo $post['nome_utente']; ?></a></li>
                                    </ul>
                                </div>
                            </div>
                            <!-- //.featured-image -->
                            <h2><?php echo $post['titolo']; ?></h2>
                            <p style="margin-bottom: 20%"><?php echo $post['contenuto']; ?></p>
                        <?php endforeach; ?>

                        <?php if ($this->valPost == 0):
                            ?>
                            <div class="col-lg-12 container-post">
                                <div class="featured-image">
                                    <img
                                        src="http://eship.dyson.cornell.edu/wp-eship/wp-content/uploads/idea-lightbulb.jpg"
                                        class="img-responsive" alt="">
                                </div>
                                <h2>Ops...</h2>
                                <p>Non hai ancora inserito alcun post, inizia ora!</p>
                                <br>
                                <br>
                                <br>
                                <div class="col-lg-12 action-started" style="margin-bottom: 20%">
                                    <a href="<?php echo $this->url(
                                        array(
                                            'controller' => 'user',
                                            'action' => 'nuovopost'
                                        )
                                    ); ?>" class="btn btn-outlined">CREA UN POST</a>
                                </div>
                            </div>
                        <?php endif; ?>

                    </div>
                    <!-- FINE POST -->
                    <?php echo $this->paginationControl($this->postSet, "Sliding", "paginatore.phtml"); ?>
                </div>

                <div class="col-lg-4 container-right-sidebar">
                    <br>
                    <br>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 cnt-form-search">
                        <form method="post" class="searchbox-container" action="<?php echo $this->url(
                            array(
                                'controller' => 'user',
                                'action' => 'cerca',
                            )); ?>">
                            <input type="search" class="searchbox" name="search" autocomplete="off"
                                   placeholder="Cerca..."/>
                            <button type="submit" class="searchbutton fa fa-search"></button>
                        </form>
                    </div>

                    <span class="dotted-line"></span>

                    <div class="col-lg-12 cnt-about-us">
                        <h3 style="text-transform: capitalize">Ciao, <?php echo $this->nome ?>!</h3>
                        <hr class="title-sidebar"/>
                        <!-- TABELLA RICHIESTE DI AMICIZIA -->
                        <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th class="font-tabella" style="text-align: center">Nuovi Amici</th>
                                <?php if (count($this->amiciSet) != 0): ?>
                                    <th class="font-tabella" style="text-align: center">Accetta</th>
                                    <th class="font-tabella" style="text-align: center">Rifiuta</th>
                                <?php endif ?>
                            </tr>
                            </thead>

                            <tbody>
                            <tr>
                                <?php for ($i = 0;
                                $i < count($this->amiciSet);
                                $i++): ?>
                                <td class="font-tabella-campi"
                                    style="text-align: center"><?php echo $this->amiciSet[$i]['richiedente']; ?></td>
                                <td style="font-size: 1.2em; text-align: center">
                                    <a href="<?php echo $this->url(
                                        array(
                                            'controller' => 'user',
                                            'action' => 'amicipost',
                                            'idamici' => $this->amiciSet[$i]['id_amici'],
                                            'azione' => 'accepted'
                                        )); ?>">
                                        <span>
                                            <i class="fa fa-check-square" style="color: #21DC7F"></i>
                                        </span>
                                    </a>
                                </td>
                                <td style="font-size: 1.2em; text-align: center">
                                    <a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'amicipost',
                                        'idamici' => $this->amiciSet[$i]['id_amici'],
                                        'azione' => 'refused'
                                    )); ?>">
                                        <span>
                                            <i class="fa fa-times-circle" style="color: #761c19"></i>
                                        </span>
                                    </a>
                                </td>
                            </tr>
                            <?php endfor; ?>
                            <?php if ($i == 0): ?>
                                <td class="font-tabella-campi" style="text-align: center">Non hai nessuna nuova
                                    richiesta!
                                </td>
                                </tr>
                            <?php endif; ?>

                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-5 col-sm-5 col-lg-5"></div>
                            <div class="col-lg-12 action-started">
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'amici'));
                                ?>" class="btn btn-outlined">Tutti gli amici <span>
                                            <i class="fa fa-arrow-right"></i>
                                        </span></a>
                            </div>
                        </div>
                        <!-- FINE TABELLA -->
                    </div>
                    <span class="dotted-line"></span>

                    <!-- TABELLA NOTIFICHE -->
                    <div class="col-lg-12 popular-posts">
                        <h3>Ultime notifiche</h3>
                        <hr class="title-sidebar"/>
                        <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                               width="100%">
                            <tbody>
                            <tr>
                                <?php for ($i = 0;
                                $i < count($this->notificaSet);
                                $i++): ?>
                                <?php if ($this->notificaSet[$i]['tipo'] == 0): ?>
                                    <td class="font-tabella-campi">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'profilo',
                                            'user' => $this->notificaSet[$i]['user']
                                        ));
                                        ?>"><?php echo $this->notificaSet[$i]['mittente']; ?></a> ha pubblicato un nuovo
                                        post
                                        in <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'visualizzablog',
                                            'blog' => $this->notificaSet[$i]['idblog']
                                        ));
                                        ?>">"<?php echo $this->notificaSet[$i]['blog']; ?>"</a>
                                        il <?php echo $this->notificaSet[$i]['data']; ?>.
                                    </td>
                                    <td style="font-size: 1.2em; text-align: center">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'nascondinotifica',
                                            'idnot' => $this->notificaSet[$i]['idnotifica'],
                                        ));
                                        ?>">
                                        <span>
                                            <i class="fa fa-times-circle" style="color: #761c19"></i>
                                        </span>
                                        </a>
                                    </td>
                                <?php elseif ($this->notificaSet[$i]['tipo'] == 1): ?>
                                    <td class="font-tabella-campi">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'profilo',
                                            'user' => $this->notificaSet[$i]['user']
                                        ));
                                        ?>"><?php echo $this->notificaSet[$i]['mittente']; ?></a> ti ha eliminato dai
                                        suoi
                                        amici.
                                    </td>
                                    <td style="font-size: 1.2em; text-align: center">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'nascondinotifica',
                                            'idnot' => $this->notificaSet[$i]['idnotifica'],
                                        ));
                                        ?>">
                                        <span>
                                            <i class="fa fa-times-circle" style="color: #761c19"></i>
                                        </span>
                                        </a>
                                    </td>
                                <?php elseif ($this->notificaSet[$i]['tipo'] == 2): ?>
                                    <td class="font-tabella-campi">
                                        Staff ha appena eliminato un tuo
                                        post dal blog "<?php echo $this->notificaSet[$i]['nome']; ?>"
                                        causa <?php echo $this->notificaSet[$i]['motivazione']; ?>.
                                    </td>
                                    <td style="font-size: 1.2em; text-align: center">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'nascondinotifica',
                                            'idnot' => $this->notificaSet[$i]['idnotifica'],
                                        ));
                                        ?>">
                                        <span>
                                            <i class="fa fa-times-circle" style="color: #761c19"></i>
                                        </span>
                                        </a>
                                    </td>
                                <?php elseif ($this->notificaSet[$i]['tipo'] == 3): ?>
                                    <td class="font-tabella-campi">
                                        Staff ha appena eliminato il tuo
                                        blog "<?php echo $this->notificaSet[$i]['nome']; ?>"
                                        causa <?php echo $this->notificaSet[$i]['motivazione']; ?>.
                                    </td>
                                    <td style="font-size: 1.2em; text-align: center">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'nascondinotifica',
                                            'idnot' => $this->notificaSet[$i]['idnotifica'],
                                        ));
                                        ?>">
                                        <span>
                                            <i class="fa fa-times-circle" style="color: #761c19"></i>
                                        </span>
                                        </a>
                                    </td>
                                <?php else: ?>
                                    <td class="font-tabella-campi">
                                        Ops... c'è qualcosa che non va in questa notifica. Contatta l'amministratore del
                                        sito per l'aiuto!
                                    </td>
                                    <td style="font-size: 1.2em; text-align: center">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'nascondinotifica',
                                            'idnot' => $this->notificaSet[$i]['idnotifica'],
                                        ));
                                        ?>">
                                        <span>
                                            <i class="fa fa-times-circle" style="color: #761c19"></i>
                                        </span>
                                        </a>
                                    </td>
                                <?php endif; ?>
                            </tr>
                            <?php endfor; ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-md-5 col-sm-5 col-lg-5"></div>
                        <div class="col-lg-12 action-started">
                            <a href="<?php echo $this->url(array(
                                'controller' => 'user',
                                'action' => 'visualizzanotifiche'),
                                null, true);
                            ?>" class="btn btn-outlined">Tutte le notifiche <span>
                                            <i class="fa fa-arrow-right"></i>
                                        </span></a>
                        </div>
                    </div>
                    <!-- FINE TABELLA -->


                </div>
            </div>
        </div>
    </div>
</section>