<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">
        </div>
    </div>
</section>

<section id="post-blog" class="main-post">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 container-post">
                    <ul class="blog-data">
                        <div class="row" style="text-align: center; margin: auto;>
							<div class=">
                            <h4 style="color: #21DC7F; font-family: 'Montserrat',sans-serif; letter-spacing: 1px; font-size: 2.5rem; padding-bottom: 1.2rem; margin-bottom: 1.2rem;">
                                Blog: <?php echo $this->titoloblog; ?></h4>
                            <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                                   width="100%">
                                <thead>
                                <tr>
                                    <th class="font-tabella" style="text-align: center">Titolo</th>
                                    <?php if (count($this->postSet)>0): ?>
                                    <th class="font-tabella" style="text-align: center">Contenuto</th>
                                    <th class="font-tabella" style="text-align: center">Data</th>
                                    <th class="font-tabella" style="text-align: center">Elimina</th>
                                    <?php endif; ?>
                                </tr>
                                </thead>

                                <tbody>
                                <tr>
                                    <?php if (count($this->postSet)==0): ?>
                                    <td class="font-tabella-campi"
                                        style="font-size: 1.4rem">Non ci sono post da visualizzare.</td>
                                    <?php endif; ?>

                                    <?php foreach ($this->postSet as $post): ?>
                                    <td class="font-tabella-campi"
                                        style="font-size: 1.4rem"><?php echo $post->titolo; ?></td>
                                    <td class="font-tabella-campi"
                                        style="font-size: 1.3rem;"><?php echo $post->contenuto; ?></td>
                                    <td class="font-tabella-campi"
                                        style="font-size: 1.2rem;"><?php echo $post->data; ?></td>
                                    <td style="font-size: 1.2em;">
                                        <a href="<?php echo $this->url(array(
                                            'controller' => 'admin',
                                            'action' => 'eliminapost',
                                            'post' => $post->id_post));
                                        ?>">
                                            <span>
                                                <i class="fa fa-times-circle"
                                                   style="color: #761c19; font-size: 1.4em"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                            <div class="row">
                                <div class="col-md-5 col-sm-5 col-lg-5"></div>
                                <div class="col-lg-12 action-started">
                                    <a href="<?php echo $this->url(array(
                                        'controller' => 'admin',
                                        'action' => 'gestioneblog'));
                                    ?>" class="btn btn-outlined">Indietro</a>
                                </div>
                            </div>
                        </div>
                </div>
                </ul>
            </div>
        </div>
    </div>
    </div>
</section>