<html>
<head>
</head>
<body>

<body class="black-background">
<div class="logo-login">
</div>

<div class="row">
    <div class="container" id="register">
        <div class="hero-text align-center" style="text-align: center">
            <h1>Conferma eliminazione</h1>
        </div>
        <div class="main-login main-center">
            <h2 style="font-size:1.6em; color: #761c19;">Stai eliminando il blog "<?php echo $this->titoloblog; ?>
                "</h2>
            <br>
            <h2 style="font-size:1.4em; color: #0a151e; margin-bottom: 20pt">Inserisci un motivo che verrà recapitato
                all'utente.</h2>
            <?php echo $this->delblogForm; ?>
        </div>
    </div>
</div>

</body>