<html>
<head>
</head>
<body>

<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">

        </div>
        <!-- //.cnt-heroblog-content -->
    </div>
</section>

<section id="post-blog" class="blog-left-sidebar">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 container-left-sidebar">
                    <br>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 cnt-admin">
                        <h3>Benvenuto,</h3>
                        <hr class="title-sidebar"/>
                        <h2 style="font-family: 'Open Sans', sans-serif; font-size: 1.5rem; margin-top: 5px; margin-bottom: 10px; width: 100%; line-height: 25px; color: #9f9f9f;">
                            sei in HOME</h2>
                    </div>
                    <span class="dotted-line"></span>

                </div>
                <div class="col-lg-8" id="container-posts-left">
                    <div class="col-lg-12 container-post">
                        <h2 style="font-size: 40pt; margin-bottom: auto; color: #21DC7F">Dashboard</h2>
                        <p style="font-size: xx-large; margin-bottom: 20px">Al momento nella tua comunità ci
                            sono <?php echo $this->numutenti; ?> iscritti.</p>

                        <?php if ($this->blogutenti == 0): ?>
                            <p style="font-size: xx-large">Gli utenti non hanno ancora pubblicato blog.</p>
                        <?php else: ?>
                            <p style="font-size: xx-large">Gli utenti hanno pubblicato <?php echo $this->blogutenti; ?>
                                blog.</p>
                        <?php endif; ?>

                    </div>

                </div>
            </div>
        </div>
    </div>
</section>


</body>
</html>