<body class="black-background">

<div class="logo-login">
</div>

<div class="row">
    <div class="container" id="register">
        <div class="main-login main-center">
            <h2 style="font-size:1.4em; color:#8d9496;">Inserisci Staff</h2>
            <br>
            <?php echo $this->registratiForm; ?>
            <hr class="separator-login">
        </div>
    </div>
</div>
</div>

</body>

<script type="text/javascript">
    $.validator.setDefaults({
        submitHandler: function () {
            $("#registrati").submit();
        }
    });

    $(document).ready(function () {
        $("#registrati").validate({
            rules: {
                Nome: "required",
                Cognome: "required",
                nascita: {
                    required: true
                },
                email: {
                    required: true,
                    email: true
                },
                username: {
                    required: true,
                    minlength: 3
                },
                password: {
                    required: true,
                    minlength: 4
                },
                password_confirm: {
                    required: true,
                    minlength: 4,
                    equalTo: "#password"
                },
                telefono: {
                    required: true,
                    digits: true
                },
                Descrizione: {
                    required: true,
                    minlength: 3
                }
            },
            messages: {
                Nome: "Inserisci il tuo nome.",
                Cognome: "Inserisci il tuo cognome.",
                nascita: {
                    required: "Il campo data di nascita non può essere vuoto.",
                    date: "Inserisci una data corretta."
                },
                email: {
                    required: "Il campo email non può essere vuoto.",
                    email: "Inserisci una email valida."
                },
                username: {
                    required: "Il campo username non può essere vuoto.",
                    minlength: "L'username deve essere almeno di 3 caratteri."
                },
                password: {
                    required: "Il campo password non può essere vuoto.",
                    minlength: "La password deve avere almeno 4 caratteri."
                },
                password_confirm: {
                    required: "Il campo password non può essere vuoto.",
                    minlength: "La password deve avere almeno 4 caratteri.",
                    equalTo: "Le passoword inserite non coincidono."
                },
                telefono: {
                    required: "Il campo telefono non può essere vuoto.",
                    digits: "Il campo telefono deve contenere soltanto caratteri numerici."
                },
                Descrizione: {
                    required: "Il campo descrizione non può essere vuoto.",
                    minlength: "La password deve avere almeno 3 caratteri."
                }
            }
        });
    });

</script>