<body class="black-background">

<div class="logo-login">
</div>

<div class="row">
    <div class="container" id="register">

        <div class="main-login main-center">
            <h2 style="font-size:1.4em; color:#8d9496;">Inserisci nuova Faq</h2>
            <br>
            <?php echo $this->formFaq; ?>
        </div>

    </div>
</div>
</div>

</body>
<script type="text/javascript">
    $.validator.setDefaults({
        submitHandler: function () {
            $("#datifaq").submit();
        }
    });

    $(document).ready(function () {
        $("#datifaq").validate({
            rules: {
                domanda: {
                    required: true,
                    minlength: 3
                },
                risposta: {
                    required: true,
                    minlength: 3
                }
            },
            messages: {
                domanda: {
                    required: "Il campo domanda non può essere vuoto.",
                    minlength: "La domanda deve essere almeno di 3 caratteri."
                },
                risposta: {
                    required: "Il campo risposta non può essere vuoto.",
                    minlength: "La risposta deve avere almeno 3 caratteri."
                }
            },
            errorElement: "em",
            errorPlacement: function (error, element) {
                // Add the `help-block` class to the error element
                error.addClass("help-block");

                // Add `has-feedback` class to the parent div.form-group
                // in order to add icons to inputs
                element.parents(".col-sm-5").addClass("has-feedback");

                if (element.prop("type") === "checkbox") {
                    error.insertAfter(element.parent("label"));
                } else {
                    error.insertAfter(element);
                }
            },
            success: function (label, element) {

            },
            highlight: function (element, errorClass, validClass) {
                $(element).parents(".col-sm-5").addClass("has-error").removeClass("has-success");
                $(element).attr("style", "border: 2px solid red");
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).parents(".col-sm-5").addClass("has-success").removeClass("has-error");
                $(element).attr("style", "2px solid #E3E7E9");
            }
        });
    });

</script>