<body class="black-background">
<div class="logo-login">
</div>

<div class="row">
    <div class="container" id="register">
        <div class="main-login main-center">

            <h2 style="font-size:1.4em; color:#8d9496;">Modifica Faq</h2>
            <br>
            <?php echo $this->formFaq; ?>

        </div>
    </div>
</div>
</div>

</body>
<script type="text/javascript">
    $.validator.setDefaults({
        submitHandler: function () {
            $("#datifaq").submit();
        }
    });

    $(document).ready(function () {
        $("#datifaq").validate({
            rules: {
                domanda: {
                    required: true,
                    minlength: 3
                },
                risposta: {
                    required: true,
                    minlength: 3
                }
            },
            messages: {
                domanda: {
                    required: "Il campo domanda non può essere vuoto.",
                    minlength: "La domanda deve essere almeno di 3 caratteri."
                },
                risposta: {
                    required: "Il campo risposta non può essere vuoto.",
                    minlength: "La risposta deve avere almeno 3 caratteri."
                }
            }
        });
    });

</script>