<html>
<head>
</head>
<body>

<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">

        </div>
        <!-- //.cnt-heroblog-content -->
    </div>
</section>

<section id="post-blog" class="blog-left-sidebar">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 container-left-sidebar">
                    <br>
                    <span class="dotted-line"></span>

                    <div class="col-lg-12 cnt-admin">
                        <h3>Benvenuto,</h3>
                        <hr class="title-sidebar"/>
                        <h2 style="font-family: 'Open Sans', sans-serif; font-size: 1.5rem; margin-top: 5px; margin-bottom: 10px; width: 100%; line-height: 25px; color: #9f9f9f;">
                            sei in HOME->GESTIONE UTENTI</h2>
                    </div>
                    <!-- AMICI -->
                    <span class="dotted-line"></span>
                    <div class="col-lg-12 cnt-about-us" style="margin-top: 5px">
                        <h3 style="text-transform: capitalize">I suoi amici</h3>
                        <hr class="title-sidebar"/>
                    <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                           width="100%">
                        <thead>
                        <tr>
                            <th class="font-tabella" style="text-align: center">Nome</th>
                            <th class="font-tabella" style="text-align: center">Profilo</th>
                        </tr>
                        </thead>

                        <tbody>
                        <tr>
                            <?php for ($i = 0;
                            $i < count($this->amiciSet);
                            $i++): ?>
                            <td class="font-tabella-campi" style="font-size: larger; text-transform: capitalize"><?php echo $this->amiciSet[$i]['amico']; ?></td>
                            <td style="font-size: 1.2em;">
                                <a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'admin',
                                        'action' => 'profilo',
                                        'user' => $this->amiciSet[$i]['username'],
                                        'id' => $this->amiciSet[$i]['idamico']
                                    )); ?>">
											<span>
                                                <i class="fa fa-arrow-right" style="color: #21DC7F"></i>
                                            </span>
                                </a>
                            </td>
                        </tr>
                        <?php endfor; ?>

                        </tbody>
                    </table>
                        </div>

                    <!-- RICHIESTE D'AMICIZIA -->
                    <span class="dotted-line"></span>
                    <div class="col-lg-12 cnt-about-us" style="margin-top: 5px">
                        <h3 style="text-transform: capitalize">Richieste</h3>
                        <hr class="title-sidebar"/>
                        <h2 style="font-family: 'Open Sans', sans-serif; font-size: 1.5rem; margin-top: 5px; margin-bottom: 10px; width: 100%; line-height: 25px; color: #9f9f9f;">
                            L'utente ha ricevuto in totale <?php echo $this->amicizie ?> richieste d'amicizia.</h2>
                        </div>
                </div>

                <!-- VISUALIZZAZIONE PROFILO E ANAGRAFICA -->
                <div class="col-lg-8" id="container-posts-left">
                    <div class="col-lg-12 container-post">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 feature-show">
                            <?php foreach ($this->datiSet as $dati): ?>
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                    <img src="<?php echo $this->baseUrl("assets/profilo/$dati->image"); ?>" alt=""
                                         class="img-responsive" style="margin-bottom: 5%">
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 content-feature">
                                    <h2 style="font-size: 30pt; margin-bottom: 10px; text-transform: capitalize; font-family: 'Open Sans', sans-serif;
                                        font-weight: 100; text-align: left; width: 80%; position: relative; top: 35px; color: #21DC7F;"><?php echo $dati->nome . ' ' . $dati->cognome; ?></h2>
                                    <h2 style="font-family: 'Open Sans',sans-serif; font-size: 1.6rem; text-align: left; margin-top: 10px; margin-bottom: auto; color: #21DC7F;">
                                        @<?php echo $dati->username; ?> </h2>
                                    <h2 style="font-family: 'Open Sans',sans-serif; font-weight: 300; font-size: 1.6rem; text-align: left; margin-top: 4px; margin-bottom: auto; color: #787878"><?php echo substr($dati->nascita, 8, 2) . "-" . substr($dati->nascita, 5, 2) . "-" . substr($dati->nascita, 0, 4) . ' - ' . $dati->email; ?></h2>

                                    <p style="margin-bottom: 5%; font-family: 'Open Sans', sans-serif; font-size: 1.6rem; color: #787878; font-weight: 400;
                                        width: 80%; position: relative; top: 40px; text-align: left;"><?php echo $dati->descrizione; ?></p>
                                </div>
                            <?php endforeach; ?>
                            <br>
                            <br>
                        </div>

                        <section id="hiring">
                            <div class="cnt-hiring-bg">
                                <div class="container" style="margin-top: 25%">
                                    <h1 style="text-align: center; font-family: 'Open Sans', sans-serif; text-transform: uppercase; font-weight: 800;
                                    font-size: 3rem; letter-spacing: 0px; margin-top: 10%; color: #3c3c4e;">I suoi
                                        blog</h1>
                                    <div class="row-centered">
                                        <div class="col-xs-12 col-md-12 col-lg-6 col-centered container-jobs">

                                            <?php if (count($this->blogSet) == 0): ?>
                                                <div class="col-xs-12 col-md-12 col-lg-12 col-centered job-position">
                                                    <div class="col-xs-12 col-md-12 col-lg-8 data-job" style="font-family: 'Open Sans', sans-serif; font-size: 1.6rem;
                                                    color: #787878; font-weight: 400; width: 80%; position: relative; top: 40px; text-align: left;">
                                                        <ul>
                                                            <li class="place" style="padding-left: 0px">Nessun blog presente!</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            <?php else: ?>
                                                <?php foreach ($this->blogSet as $blg): ?>
                                                    <div
                                                        class="col-xs-12 col-md-12 col-lg-12 col-centered job-position">
                                                        <div class="col-xs-12 col-md-12 col-lg-8 data-job">
                                                            <ul>
                                                                <li class="place" style="padding-left: 0px"><?php if (strlen($blg->titolo) > 8) echo substr($blg->titolo, 0, 8) . '...'; else echo $blg->titolo; ?></li>
                                                                <li class="title-job" style="padding-left: 0px"><?php if (strlen($blg->descrizione) > 8) echo substr($blg->descrizione, 0, 8) . '...'; else echo $blg->descrizione; ?></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>

                    </div>
                </div>
            </div>
        </div>
</section>


</body>
</html>