<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">
        </div>
    </div>
</section>

<section id="post-blog" class="main-post">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row" style="text-align: center; margin: auto;">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 container-post">
                    <ul class="blog-data">
                        <div class="row">
                            <div class="col-md-12">
                                <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                                       width="100%">
                                    <thead>
                                    <tr>
                                        <th class="font-tabella" style="text-align: center">Nome</th>
                                        <th class="font-tabella" style="text-align: center">Cognome</th>
                                        <th class="font-tabella" style="text-align: center">E-mail</th>
                                        <th class="font-tabella" style="text-align: center">Username</th>
                                        <th class="font-tabella" style="text-align: center">Ruolo</th>
                                        <th class="font-tabella" style="text-align: center">Profilo</th>
                                        <th class="font-tabella" style="text-align: center">Modifica</th>
                                        <th class="font-tabella" style="text-align: center">Elimina</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    <tr>
                                        <?php foreach ($this->utentiSet as $utente): ?>
                                        <td class="font-tabella-campi"
                                            style="text-transform: capitalize"><?php echo $utente->nome; ?></td>
                                        <td class="font-tabella-campi"
                                            style="text-transform: capitalize"><?php echo $utente->cognome; ?></td>
                                        <td class="font-tabella-campi"><?php echo $utente->email; ?></td>
                                        <td class="font-tabella-campi"><?php echo $utente->username; ?></td>
                                        <td class="font-tabella-campi"><?php echo $utente->ruolo; ?></td>
                                        <td style="font-size: 1.4em;">
                                            <a href="<?php echo $this->url(
                                                array(
                                                    'controller' => 'admin',
                                                    'action' => 'profilo',
                                                    'id' => $utente->id_utente,
                                                    'user' => $utente->username
                                                )); ?>">
												<span>
                                                    <i class="fa fa-arrow-right" style="color: #21DC7F"></i>
                                                </span>
                                            </a>
                                        </td>
                                        <td style="font-size: 1.4em;">
                                            <a href="<?php echo $this->url(
                                                array(
                                                    'controller' => 'admin',
                                                    'action' => 'modificautente',
                                                    'utente' => $utente->id_utente
                                                )); ?>">
												<span>
                                                    <i class="fa fa-pencil" style="color: #3a579e"></i>
                                                </span>
                                            </a>
                                        </td>
                                        <td style="font-size: 1.4em;">
                                            <a href="<?php echo $this->url(array(
                                                'controller' => 'admin',
                                                'action' => 'eliminautente',
                                                'utente' => $utente->id_utente,
                                                'ruolo' => 'user'));
                                            ?>">
												<span>
                                                    <i class="fa fa-trash" style="color: #c0392b"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>

                                    </tbody>
                                </table>

                            </div>
                        </div>


                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>