<section id="hero" class="hero-blog">
    <div id="particles-js">
        <div class="cnt-heroblog-content">

        </div>
        <!-- //.cnt-heroblog-content -->
    </div>
</section>


<section id="post-blog" class="main-post">
    <div class="cnt-post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 container-post">
                    <ul class="blog-data">
                        <div class="row" style="text-align: center; margin: auto;>
							<div class=" col-md-12
                        ">
                        <table id="datatable" class="table table-striped table-bordered " cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th class="font-tabella" style="text-align: center">#</th>
                                <th class="font-tabella" style="text-align: center">Domanda</th>
                                <th class="font-tabella" style="text-align: center">Risposta</th>
                                <th class="font-tabella" style="text-align: center">Modifica</th>
                                <th class="font-tabella" style="text-align: center">Elimina</th>
                            </tr>
                            </thead>

                            <tbody>
                            <tr>
                                <?php foreach ($this->faqSet as $faq): ?>
                                <td class="font-tabella-campi"><?php echo $faq->id_faq; ?></td>
                                <td class="font-tabella-campi"><?php echo $faq->domanda; ?></td>
                                <td class="font-tabella-campi"><?php echo $faq->risposta; ?></td>
                                <td style="font-size: 1.2em;">
                                    <a href="<?php echo $this->url(
                                        array(
                                            'controller' => 'admin',
                                            'action' => 'modificafaq',
                                            'faq' => $faq->id_faq
                                        )); ?>">
                                        <button type="button"
                                                class="btn btn-lg btn-primary btn-block btn-signin button-blue-nic">
                                            Modifica
                                        </button>
                                    </a>
                                </td>
                                <td style="font-size: 1.2em;">
                                    <a href="<?php echo $this->url(array(
                                        'controller' => 'admin',
                                        'action' => 'eliminafaq',
                                        'faq' => $faq->id_faq));
                                    ?>">
                                        <button type="button"
                                                class="btn btn-lg btn-primary btn-block btn-signin button-red-nic">
                                            Elimina
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach; ?>

                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-5 col-sm-5 col-lg-5"></div>
                            <div class="col-lg-12 action-started">
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'admin',
                                    'action' => 'inseriscifaq'));
                                ?>" class="btn btn-outlined">Inserisci una nuova faq</a>
                            </div>
                        </div>
                </div>
            </div>
            </ul>
        </div>
    </div>
    </div>
    </div>
</section>